<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.4.537">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Maaruni">
<meta name="dcterms.date" content="2024-01-22">

<title>IS415-GAA - Take Home Exercise 1</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="../../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../../site_libs/clipboard/clipboard.min.js"></script>
<script src="../../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../../site_libs/quarto-search/fuse.min.js"></script>
<script src="../../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../../">
<script src="../../site_libs/quarto-html/quarto.js"></script>
<script src="../../site_libs/quarto-html/popper.min.js"></script>
<script src="../../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../../site_libs/quarto-html/anchor.min.js"></script>
<link href="../../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../../site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../../site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>


<link rel="stylesheet" href="../../styles.css">
</head>

<body class="nav-fixed">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a class="navbar-brand" href="../../index.html">
    <span class="navbar-title">IS415-GAA</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-hands-on-exercise" role="button" data-bs-toggle="dropdown" aria-expanded="false">
 <span class="menu-text">Hands-on Exercise</span>
    </a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-hands-on-exercise">    
        <li>
    <a class="dropdown-item" href="../../Hands-on_Ex/Hands-on_Ex-01/Hands-on_Ex01.html">
 <span class="dropdown-text">Hands-on Exercise 1</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../Hands-on_Ex/Hands-on_Ex-02/Hands-on_Ex02.html">
 <span class="dropdown-text">Hands-on Exercise 2</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../Hands-on_Ex/Hands-on_Ex-03/Hands-on_Ex03.html">
 <span class="dropdown-text">Hands-on Exercise 3</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../Hands-on_Ex/Hands-on_Ex-04/Hands-on_Ex04.html">
 <span class="dropdown-text">Hands-on Exercise 4</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../Hands-on_Ex/Hands-on_Ex-05/Hands-on_Ex05.html">
 <span class="dropdown-text">Hands-on Exercise 5</span></a>
  </li>  
    </ul>
  </li>
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-in-class-exercise" role="button" data-bs-toggle="dropdown" aria-expanded="false">
 <span class="menu-text">In-class Exercise</span>
    </a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-in-class-exercise">    
        <li>
    <a class="dropdown-item" href="../../In-class_Ex/In-class_Ex02/Inclass_Ex02.html">
 <span class="dropdown-text">In-class Exercise 2</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../In-class_Ex/In-class_Ex03/In-class_Ex03_1.html">
 <span class="dropdown-text">In-class Exercise 3</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../In-class_Ex/In-class_Ex04/Inclass_Ex04.html">
 <span class="dropdown-text">In-class Exercise 4</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../In-class_Ex/In-class_Ex05/Inclass_Ex05.html">
 <span class="dropdown-text">In-class Exercise 5</span></a>
  </li>  
    </ul>
  </li>
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-take-home-exercise" role="button" data-bs-toggle="dropdown" aria-expanded="false">
 <span class="menu-text">Take-home Exercise</span>
    </a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-take-home-exercise">    
        <li>
    <a class="dropdown-item" href="../../Take-home_Ex/Take-home_Ex01/Take-home_Ex01_3.html">
 <span class="dropdown-text">Take-home Exercise 1</span></a>
  </li>  
    </ul>
  </li>
</ul>
            <ul class="navbar-nav navbar-nav-scroll ms-auto">
  <li class="nav-item">
    <a class="nav-link" href="../../index.html"> 
<span class="menu-text">Home</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../about.html"> 
<span class="menu-text">About</span></a>
  </li>  
</ul>
          </div> <!-- /navcollapse -->
          <div class="quarto-navbar-tools">
</div>
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#overview" id="toc-overview" class="nav-link active" data-scroll-target="#overview">Overview</a>
  <ul class="collapse">
  <li><a href="#setting-the-scene" id="toc-setting-the-scene" class="nav-link" data-scroll-target="#setting-the-scene">Setting the Scene</a></li>
  <li><a href="#objectives" id="toc-objectives" class="nav-link" data-scroll-target="#objectives">Objectives</a></li>
  <li><a href="#the-task" id="toc-the-task" class="nav-link" data-scroll-target="#the-task"><strong>The Task</strong></a></li>
  </ul></li>
  <li><a href="#getting-started" id="toc-getting-started" class="nav-link" data-scroll-target="#getting-started">Getting Started</a>
  <ul class="collapse">
  <li><a href="#data-acquisition" id="toc-data-acquisition" class="nav-link" data-scroll-target="#data-acquisition">Data Acquisition</a></li>
  <li><a href="#installing-and-loading-packages" id="toc-installing-and-loading-packages" class="nav-link" data-scroll-target="#installing-and-loading-packages"><strong>Installing and Loading Packages</strong></a></li>
  </ul></li>
  <li><a href="#importing-and-preparing-grab-aspatial-data" id="toc-importing-and-preparing-grab-aspatial-data" class="nav-link" data-scroll-target="#importing-and-preparing-grab-aspatial-data"><strong>Importing and Preparing Grab Aspatial Data</strong></a></li>
  <li><a href="#importing-and-preparing-geospatial-data" id="toc-importing-and-preparing-geospatial-data" class="nav-link" data-scroll-target="#importing-and-preparing-geospatial-data"><strong>Importing and Preparing Geospatial Data</strong></a>
  <ul class="collapse">
  <li><a href="#mapping-the-geospatial-data-sets" id="toc-mapping-the-geospatial-data-sets" class="nav-link" data-scroll-target="#mapping-the-geospatial-data-sets"><strong>MAPPING THE GEOSPATIAL DATA SETS</strong></a></li>
  <li><a href="#geospatial-data-wrangling" id="toc-geospatial-data-wrangling" class="nav-link" data-scroll-target="#geospatial-data-wrangling"><strong>GEOSPATIAL DATA WRANGLING</strong></a>
  <ul class="collapse">
  <li><a href="#converting-sf-data-frames-to-sps-spatial-class" id="toc-converting-sf-data-frames-to-sps-spatial-class" class="nav-link" data-scroll-target="#converting-sf-data-frames-to-sps-spatial-class"><strong>CONVERTING SF DATA FRAMES TO SP’S SPATIAL* CLASS</strong></a></li>
  <li><a href="#converting-the-spatial-class-into-generic-sp-format" id="toc-converting-the-spatial-class-into-generic-sp-format" class="nav-link" data-scroll-target="#converting-the-spatial-class-into-generic-sp-format"><strong>CONVERTING THE SPATIAL* CLASS INTO GENERIC SP FORMAT</strong></a></li>
  <li><a href="#converting-the-generic-sp-format-into-spatstats-ppp-format" id="toc-converting-the-generic-sp-format-into-spatstats-ppp-format" class="nav-link" data-scroll-target="#converting-the-generic-sp-format-into-spatstats-ppp-format"><strong>CONVERTING THE GENERIC SP FORMAT INTO SPATSTAT’S PPP FORMAT</strong></a></li>
  <li><a href="#handling-duplicated-points" id="toc-handling-duplicated-points" class="nav-link" data-scroll-target="#handling-duplicated-points"><strong>HANDLING DUPLICATED POINTS</strong></a></li>
  <li><a href="#creating-owin-object" id="toc-creating-owin-object" class="nav-link" data-scroll-target="#creating-owin-object"><strong>CREATING <em>OWIN</em> OBJECT</strong></a></li>
  <li><a href="#combining-point-events-object-and-owin-object" id="toc-combining-point-events-object-and-owin-object" class="nav-link" data-scroll-target="#combining-point-events-object-and-owin-object"><strong>COMBINING POINT EVENTS OBJECT AND OWIN OBJECT</strong></a></li>
  </ul></li>
  <li><a href="#first-order-spatial-point-patterns-analysis" id="toc-first-order-spatial-point-patterns-analysis" class="nav-link" data-scroll-target="#first-order-spatial-point-patterns-analysis"><strong>FIRST-ORDER SPATIAL POINT PATTERNS ANALYSIS</strong></a>
  <ul class="collapse">
  <li><a href="#kernel-density-estimation" id="toc-kernel-density-estimation" class="nav-link" data-scroll-target="#kernel-density-estimation"><strong>KERNEL DENSITY ESTIMATION</strong></a></li>
  <li><a href="#working-with-different-automatic-badwidth-methods" id="toc-working-with-different-automatic-badwidth-methods" class="nav-link" data-scroll-target="#working-with-different-automatic-badwidth-methods"><strong>WORKING WITH DIFFERENT AUTOMATIC BADWIDTH METHODS</strong></a></li>
  <li><a href="#working-with-different-kernel-methods" id="toc-working-with-different-kernel-methods" class="nav-link" data-scroll-target="#working-with-different-kernel-methods">WORKING WITH DIFFERENT KERNEL METHODS</a></li>
  </ul></li>
  <li><a href="#fixed-and-adaptive-kde" id="toc-fixed-and-adaptive-kde" class="nav-link" data-scroll-target="#fixed-and-adaptive-kde"><strong>FIXED AND ADAPTIVE KDE</strong></a>
  <ul class="collapse">
  <li><a href="#computing-kde-by-using-fixed-bandwidth" id="toc-computing-kde-by-using-fixed-bandwidth" class="nav-link" data-scroll-target="#computing-kde-by-using-fixed-bandwidth"><strong>COMPUTING KDE BY USING FIXED BANDWIDTH</strong></a></li>
  <li><a href="#computing-kde-by-using-adaptive-bandwidth" id="toc-computing-kde-by-using-adaptive-bandwidth" class="nav-link" data-scroll-target="#computing-kde-by-using-adaptive-bandwidth"><strong>COMPUTING KDE BY USING ADAPTIVE BANDWIDTH</strong></a></li>
  <li><a href="#converting-kde-output-into-grid-object." id="toc-converting-kde-output-into-grid-object." class="nav-link" data-scroll-target="#converting-kde-output-into-grid-object."><strong>CONVERTING KDE OUTPUT INTO GRID OBJECT.</strong></a></li>
  <li><a href="#visualising-the-output-in-tmap" id="toc-visualising-the-output-in-tmap" class="nav-link" data-scroll-target="#visualising-the-output-in-tmap"><strong>VISUALISING THE OUTPUT IN TMAP</strong></a></li>
  <li><a href="#comparing-spatial-point-patterns-using-kde" id="toc-comparing-spatial-point-patterns-using-kde" class="nav-link" data-scroll-target="#comparing-spatial-point-patterns-using-kde"><strong>COMPARING SPATIAL POINT PATTERNS USING KDE</strong></a></li>
  </ul></li>
  <li><a href="#nearest-neighbour-analysis" id="toc-nearest-neighbour-analysis" class="nav-link" data-scroll-target="#nearest-neighbour-analysis"><strong>NEAREST NEIGHBOUR ANALYSIS</strong></a>
  <ul class="collapse">
  <li><a href="#testing-spatial-point-patterns-using-clark-and-evans-test" id="toc-testing-spatial-point-patterns-using-clark-and-evans-test" class="nav-link" data-scroll-target="#testing-spatial-point-patterns-using-clark-and-evans-test"><strong>TESTING SPATIAL POINT PATTERNS USING CLARK AND EVANS TEST</strong></a></li>
  <li><a href="#section" id="toc-section" class="nav-link" data-scroll-target="#section"></a></li>
  <li><a href="#clark-and-evans-test-choa-chu-kang-planning-area" id="toc-clark-and-evans-test-choa-chu-kang-planning-area" class="nav-link" data-scroll-target="#clark-and-evans-test-choa-chu-kang-planning-area"><strong>CLARK AND EVANS TEST: CHOA CHU KANG PLANNING AREA</strong></a></li>
  <li><a href="#clark-and-evans-test-changi-planning-area" id="toc-clark-and-evans-test-changi-planning-area" class="nav-link" data-scroll-target="#clark-and-evans-test-changi-planning-area"><strong>CLARK AND EVANS TEST: CHANGI PLANNING AREA</strong></a></li>
  </ul></li>
  <li><a href="#network-constraint-layers" id="toc-network-constraint-layers" class="nav-link" data-scroll-target="#network-constraint-layers">Network constraint layers</a>
  <ul class="collapse">
  <li><a href="#generating-line-centre-points" id="toc-generating-line-centre-points" class="nav-link" data-scroll-target="#generating-line-centre-points"><strong>7.6.2 GENERATING LINE CENTRE POINTS</strong></a></li>
  <li><a href="#performing-netkde" id="toc-performing-netkde" class="nav-link" data-scroll-target="#performing-netkde"><strong>7.6.3 PERFORMING NETKDE</strong></a></li>
  </ul></li>
  </ul></li>
  <li><a href="#references" id="toc-references" class="nav-link" data-scroll-target="#references">References</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Take Home Exercise 1</h1>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Maaruni </p>
          </div>
  </div>
    
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">January 22, 2024</p>
    </div>
  </div>
  
    
  </div>
  


</header>


<section id="overview" class="level1">
<h1>Overview</h1>
<section id="setting-the-scene" class="level2">
<h2 class="anchored" data-anchor-id="setting-the-scene">Setting the Scene</h2>
<p>Human mobility, the movement of human beings in space and time, reflects the spatial-temporal characteristics of human behavior. With the advancement Information and Communication Technologies (ICT) especially smart phone, a large volume of data related to human mobility have been collected. By using appropriate GIS analysis methods, these data are potentially useful in supporting smart city planning and management.</p>
<p>In Singapore, one of the important source of data related to human mobility is from <a href="https://datamall.lta.gov.sg/content/datamall/en.html">Land Transport Authority (LTA) DataMall</a>. Two data sets related to human mobility are provided by the portal, they are: Passenger Volume by Origin Destination Train Stations and Passenger Volume by Origin Destination Bus Stops. One of the limitation of these data sets is that their location are biased to either bus stops or MRT/LRT stations. In 2020, another very interesting human mobility data set called <a href="https://engineering.grab.com/grab-posisi">Grab Posisi</a> was released by GRAB, one of the largest shared taxi operator in South-east Asia. There are two data sets been released and one of them is for Singapore.</p>
<p>Grab is one of the most frequently used services in Singapore, with ride hailing services to ordering food to be delivered via Grab. In this assignment we will be looking at Grab’s ride hailing services by looking at the end destinations of users taking trips and see its distribution across Singapore and specifically Singapore’s roads. This will be useful in identifying congestion rates and much more at these roads.</p>
</section>
<section id="objectives" class="level2">
<h2 class="anchored" data-anchor-id="objectives">Objectives</h2>
<p>Geospatial analytics hold tremendous potential to address complex problems facing society. In this study, you are tasked to apply appropriate spatial point patterns analysis methods to discover the geographical and spatio-temporal distribution of Grab hailing services locations in Singapore.</p>
</section>
<section id="the-task" class="level2">
<h2 class="anchored" data-anchor-id="the-task"><strong>The Task</strong></h2>
<p>The specific tasks of this take-home exercise are as follows:</p>
<p>Using appropriate function of <strong>sf</strong> and <strong>tidyverse</strong>, preparing the following geospatial data layer in sf tibble data.frames:</p>
<ul>
<li><p>Grab taxi location points either by origins or destinations.</p></li>
<li><p>Road layer within Singapore excluding outer islands.</p></li>
<li><p>Singapore boundary layer excluding outer islands</p></li>
</ul>
<p>Using the extracted data, derive traditional Kernel Density Estimation layers.</p>
<p>Using the extracted data, derive either Network Kernel Density Estimation (NKDE) or Temporal Network Kernel Density Estimation (TNKDE)</p>
<p>Using appropriate <strong>tmap</strong> functions, display the kernel density layers on openstreetmap of Singapore.</p>
<p>Describe the spatial patterns revealed by the kernel density maps</p>
</section>
</section>
<section id="getting-started" class="level1">
<h1>Getting Started</h1>
<section id="data-acquisition" class="level2">
<h2 class="anchored" data-anchor-id="data-acquisition">Data Acquisition</h2>
<table class="table">
<thead>
<tr class="header">
<th>Dataset Name</th>
<th>Source</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Grab Posisi Dataset</td>
<td><a href="https://engineering.grab.com/grab-posisi" class="uri">https://engineering.grab.com/grab-posisi</a></td>
</tr>
<tr class="even">
<td>MPSZ-2019 Zonal data of Singapore</td>
<td>Master Plan 2019 Subzone Boundary (No Sea) from Data.gov.sg</td>
</tr>
<tr class="odd">
<td>Coastal Boundary Data of Singapore (ESRI shapefile format)</td>
<td>Provided by SLA</td>
</tr>
<tr class="even">
<td>OpenStreetMap Road Network Dataset</td>
<td><a href="https://download.geofabrik.de/">Geofabrik download server</a>.</td>
</tr>
</tbody>
</table>
</section>
<section id="installing-and-loading-packages" class="level2">
<h2 class="anchored" data-anchor-id="installing-and-loading-packages"><strong>Installing and Loading Packages</strong></h2>
<p>Lets install the relevant R libraries needed using pacman.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a>pacman<span class="sc">::</span><span class="fu">p_load</span>(sf, spNetwork, tmap, classInt, viridis, tidyverse, list, arrow, lubridate, tidyverse, readr, sp, maptools, raster, spatstat, spdep)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
</section>
<section id="importing-and-preparing-grab-aspatial-data" class="level1">
<h1><strong>Importing and Preparing Grab Aspatial Data</strong></h1>
<p>Reading the grab aspatial data:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a>df <span class="ot">&lt;-</span> <span class="fu">read_parquet</span>(<span class="st">"../../data/GrabPosisi/part-00000.parquet"</span>)</span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a>df</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 3,034,553 × 9
   trj_id driving_mode osname pingtimestamp rawlat rawlng speed bearing accuracy
   &lt;chr&gt;  &lt;chr&gt;        &lt;chr&gt;          &lt;int&gt;  &lt;dbl&gt;  &lt;dbl&gt; &lt;dbl&gt;   &lt;int&gt;    &lt;dbl&gt;
 1 70014  car          andro…    1554943236   1.34   104. 18.9      248     3.9 
 2 73573  car          andro…    1555582623   1.32   104. 17.7       44     4   
 3 75567  car          andro…    1555141026   1.33   104. 14.0       34     3.9 
 4 1410   car          andro…    1555731693   1.26   104. 13.0      181     4   
 5 4354   car          andro…    1555584497   1.28   104. 14.8       93     3.9 
 6 32630  car          andro…    1555395258   1.30   104. 23.2       73     3.9 
 7 64631  car          andro…    1554768955   1.35   104.  0         82     3   
 8 76484  car          andro…    1554783532   1.34   104.  3.98     321     3.65
 9 65747  car          ios       1554898418   1.29   104.  4.68     324    50   
10 60478  car          ios       1555593189   1.33   104. 16.5       31    16   
# ℹ 3,034,543 more rows</code></pre>
</div>
</div>
<p>Next we need to find the starting or ending points of trips which can be done by grouping the trips by their trip_id and sorting the entries by their timestamp. Naturally, the entry of a trip_id with the earlier timestamp will be when the user boarded the car and the latest timestamp entry will reveal the destinations. First we need ton convert the timestamps to datetime format for efficient sorting.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a>df<span class="sc">$</span>pingtimestamp <span class="ot">&lt;-</span> <span class="fu">as_datetime</span>(df<span class="sc">$</span>pingtimestamp)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Grab taxi location points either by origins:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a>origin_df <span class="ot">&lt;-</span> df <span class="sc">%&gt;%</span></span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(trj_id) <span class="sc">%&gt;%</span></span>
<span id="cb5-3"><a href="#cb5-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">arrange</span>(pingtimestamp) <span class="sc">%&gt;%</span></span>
<span id="cb5-4"><a href="#cb5-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(<span class="fu">row_number</span>()<span class="sc">==</span><span class="dv">1</span>) <span class="sc">%&gt;%</span></span>
<span id="cb5-5"><a href="#cb5-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">weekday =</span> <span class="fu">wday</span>(pingtimestamp,</span>
<span id="cb5-6"><a href="#cb5-6" aria-hidden="true" tabindex="-1"></a>                        <span class="at">label=</span><span class="cn">TRUE</span>,</span>
<span id="cb5-7"><a href="#cb5-7" aria-hidden="true" tabindex="-1"></a>                        <span class="at">abbr=</span><span class="cn">TRUE</span>),</span>
<span id="cb5-8"><a href="#cb5-8" aria-hidden="true" tabindex="-1"></a>         <span class="at">start_hr =</span> <span class="fu">factor</span>(<span class="fu">hour</span>(pingtimestamp)),</span>
<span id="cb5-9"><a href="#cb5-9" aria-hidden="true" tabindex="-1"></a>         <span class="at">day =</span> <span class="fu">factor</span>(<span class="fu">mday</span>(pingtimestamp)))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Grab taxi location points either by destinations:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a>destination_df <span class="ot">&lt;-</span> df <span class="sc">%&gt;%</span></span>
<span id="cb6-2"><a href="#cb6-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(trj_id) <span class="sc">%&gt;%</span></span>
<span id="cb6-3"><a href="#cb6-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">arrange</span>(<span class="fu">desc</span>(pingtimestamp)) <span class="sc">%&gt;%</span></span>
<span id="cb6-4"><a href="#cb6-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(<span class="fu">row_number</span>()<span class="sc">==</span><span class="dv">1</span>) <span class="sc">%&gt;%</span></span>
<span id="cb6-5"><a href="#cb6-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">weekday =</span> <span class="fu">wday</span>(pingtimestamp,</span>
<span id="cb6-6"><a href="#cb6-6" aria-hidden="true" tabindex="-1"></a>                        <span class="at">label=</span><span class="cn">TRUE</span>,</span>
<span id="cb6-7"><a href="#cb6-7" aria-hidden="true" tabindex="-1"></a>                        <span class="at">abbr=</span><span class="cn">TRUE</span>),</span>
<span id="cb6-8"><a href="#cb6-8" aria-hidden="true" tabindex="-1"></a>         <span class="at">end_hr =</span> <span class="fu">factor</span>(<span class="fu">hour</span>(pingtimestamp)),</span>
<span id="cb6-9"><a href="#cb6-9" aria-hidden="true" tabindex="-1"></a>         <span class="at">day =</span> <span class="fu">factor</span>(<span class="fu">mday</span>(pingtimestamp)))</span>
<span id="cb6-10"><a href="#cb6-10" aria-hidden="true" tabindex="-1"></a>destination_df</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 28,000 × 12
# Groups:   trj_id [28,000]
   trj_id driving_mode osname  pingtimestamp       rawlat rawlng speed bearing
   &lt;chr&gt;  &lt;chr&gt;        &lt;chr&gt;   &lt;dttm&gt;               &lt;dbl&gt;  &lt;dbl&gt; &lt;dbl&gt;   &lt;int&gt;
 1 54687  car          android 2019-04-21 23:56:37   1.44   104.  1.19     299
 2 81574  car          ios     2019-04-21 23:56:33   1.34   104. 17.4      117
 3 17190  car          android 2019-04-21 23:56:30   1.34   104.  9.09     201
 4 13793  car          android 2019-04-21 23:56:25   1.32   104.  5.55     180
 5 39014  car          ios     2019-04-21 23:56:11   1.33   104. 14.1      179
 6 41170  car          ios     2019-04-21 23:56:09   1.32   104. 13.0       73
 7 64519  car          ios     2019-04-21 23:55:36   1.43   104. 12.6      210
 8 70461  car          ios     2019-04-21 23:55:29   1.29   104.  7.53      53
 9 41154  car          ios     2019-04-21 23:54:49   1.32   104. 14.4      163
10 5452   car          ios     2019-04-21 23:54:28   1.33   104. 12.0      347
# ℹ 27,990 more rows
# ℹ 4 more variables: accuracy &lt;dbl&gt;, weekday &lt;ord&gt;, end_hr &lt;fct&gt;, day &lt;fct&gt;</code></pre>
</div>
</div>
<p>Lets preview the destination_df:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(destination_df)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 6 × 12
# Groups:   trj_id [6]
  trj_id driving_mode osname  pingtimestamp       rawlat rawlng speed bearing
  &lt;chr&gt;  &lt;chr&gt;        &lt;chr&gt;   &lt;dttm&gt;               &lt;dbl&gt;  &lt;dbl&gt; &lt;dbl&gt;   &lt;int&gt;
1 54687  car          android 2019-04-21 23:56:37   1.44   104.  1.19     299
2 81574  car          ios     2019-04-21 23:56:33   1.34   104. 17.4      117
3 17190  car          android 2019-04-21 23:56:30   1.34   104.  9.09     201
4 13793  car          android 2019-04-21 23:56:25   1.32   104.  5.55     180
5 39014  car          ios     2019-04-21 23:56:11   1.33   104. 14.1      179
6 41170  car          ios     2019-04-21 23:56:09   1.32   104. 13.0       73
# ℹ 4 more variables: accuracy &lt;dbl&gt;, weekday &lt;ord&gt;, end_hr &lt;fct&gt;, day &lt;fct&gt;</code></pre>
</div>
</div>
</section>
<section id="importing-and-preparing-geospatial-data" class="level1">
<h1><strong>Importing and Preparing Geospatial Data</strong></h1>
<p>We need to retrieve the coastal outline of Singapore so that we are able to fetch the grab trips specifically within these boundaries.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb10"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a>sg_sf <span class="ot">&lt;-</span> <span class="fu">st_read</span>(<span class="at">dsn =</span> <span class="st">"../../data/geospatial"</span>, <span class="at">layer=</span><span class="st">"CostalOutline"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Reading layer `CostalOutline' from data source 
  `/Users/maarunipandithurai/Documents/maars202/geospatial/IS415-GAA/data/geospatial' 
  using driver `ESRI Shapefile'
Simple feature collection with 60 features and 4 fields
Geometry type: POLYGON
Dimension:     XY
Bounding box:  xmin: 2663.926 ymin: 16357.98 xmax: 56047.79 ymax: 50244.03
Projected CRS: SVY21</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb12"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a>mpsz_sf <span class="ot">&lt;-</span> <span class="fu">st_read</span>(<span class="at">dsn =</span> <span class="st">"../../data/geospatial"</span>, <span class="at">layer =</span> <span class="st">"MP14_SUBZONE_WEB_PL"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Reading layer `MP14_SUBZONE_WEB_PL' from data source 
  `/Users/maarunipandithurai/Documents/maars202/geospatial/IS415-GAA/data/geospatial' 
  using driver `ESRI Shapefile'
Simple feature collection with 323 features and 15 fields
Geometry type: MULTIPOLYGON
Dimension:     XY
Bounding box:  xmin: 2667.538 ymin: 15748.72 xmax: 56396.44 ymax: 50256.33
Projected CRS: SVY21</code></pre>
</div>
<div class="sourceCode cell-code" id="cb14"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a><span class="co">#mpsz_sf &lt;- st_read(dsn = "../../data/takehomeassigment1/MPSZ-2019", layer = "MPSZ-2019")</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<section id="mapping-the-geospatial-data-sets" class="level3">
<h3 class="anchored" data-anchor-id="mapping-the-geospatial-data-sets"><strong>MAPPING THE GEOSPATIAL DATA SETS</strong></h3>
<p>After checking the referencing system of each geospatial data data frame, it is also useful for us to plot a map to show their spatial patterns.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb15"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(sg_sf)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Take-home_Ex01_3_files/figure-html/unnamed-chunk-9-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb16"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(mpsz_sf)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Take-home_Ex01_3_files/figure-html/unnamed-chunk-10-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>We need to extract the geospatial data present in the aspatial dataset in the columns “rawlng” and “rawlat” and transform it to fit Singapore’s Coordinate system using crs = 3414.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb17"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a>trips_sf <span class="ot">&lt;-</span> <span class="fu">st_as_sf</span>(destination_df, </span>
<span id="cb17-2"><a href="#cb17-2" aria-hidden="true" tabindex="-1"></a>                       <span class="at">coords =</span> <span class="fu">c</span>(<span class="st">"rawlng"</span>, <span class="st">"rawlat"</span>),</span>
<span id="cb17-3"><a href="#cb17-3" aria-hidden="true" tabindex="-1"></a>                       <span class="at">crs=</span><span class="dv">4326</span>) <span class="sc">%&gt;%</span></span>
<span id="cb17-4"><a href="#cb17-4" aria-hidden="true" tabindex="-1"></a><span class="fu">st_transform</span>(<span class="at">crs =</span> <span class="dv">3414</span>)</span>
<span id="cb17-5"><a href="#cb17-5" aria-hidden="true" tabindex="-1"></a><span class="fu">glimpse</span>(trips_sf)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Rows: 28,000
Columns: 11
Groups: trj_id [28,000]
$ trj_id        &lt;chr&gt; "54687", "81574", "17190", "13793", "39014", "41170", "6…
$ driving_mode  &lt;chr&gt; "car", "car", "car", "car", "car", "car", "car", "car", …
$ osname        &lt;chr&gt; "android", "ios", "android", "android", "ios", "ios", "i…
$ pingtimestamp &lt;dttm&gt; 2019-04-21 23:56:37, 2019-04-21 23:56:33, 2019-04-21 23…
$ speed         &lt;dbl&gt; 1.190000, 17.374184, 9.088703, 5.552219, 14.058416, 12.9…
$ bearing       &lt;int&gt; 299, 117, 201, 180, 179, 73, 210, 53, 163, 347, 22, 193,…
$ accuracy      &lt;dbl&gt; 3.605, 8.000, 4.000, 3.900, 4.000, 5.000, 8.000, 10.000,…
$ weekday       &lt;ord&gt; Sun, Sun, Sun, Sun, Sun, Sun, Sun, Sun, Sun, Sun, Sun, S…
$ end_hr        &lt;fct&gt; 23, 23, 23, 23, 23, 23, 23, 23, 23, 23, 23, 23, 23, 23, …
$ day           &lt;fct&gt; 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, …
$ geometry      &lt;POINT [m]&gt; POINT (22837.7 46850), POINT (43956.34 35640.34), …</code></pre>
</div>
</div>
<p>Since we are only using the geometry data as part of our analysis let’s grab that column only and view it.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb19"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a>trips_sf_geometry <span class="ot">&lt;-</span> trips_sf<span class="sc">$</span>geometry</span>
<span id="cb19-2"><a href="#cb19-2" aria-hidden="true" tabindex="-1"></a>trips_sf_geometry</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Geometry set for 28000 features 
Geometry type: POINT
Dimension:     XY
Bounding box:  xmin: 3638.685 ymin: 25350.05 xmax: 50024.92 ymax: 49469.41
Projected CRS: SVY21 / Singapore TM
First 5 geometries:</code></pre>
</div>
</div>
<p>Notice that all the geospatial layers are within the same map extend. This shows that their referencing system and coordinate values are referred to similar spatial context. This is very important in any geospatial analysis.</p>
<p>Alternatively, we can also prepare a pin map by using the code chunk below.</p>
<p>Plotting the grab taxi data:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb21"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a><span class="co">#using 'plot' as 'view' does not render on html page</span></span>
<span id="cb21-2"><a href="#cb21-2" aria-hidden="true" tabindex="-1"></a><span class="fu">tmap_mode</span>(<span class="st">'plot'</span>)</span>
<span id="cb21-3"><a href="#cb21-3" aria-hidden="true" tabindex="-1"></a><span class="fu">tm_shape</span>(trips_sf_geometry)<span class="sc">+</span></span>
<span id="cb21-4"><a href="#cb21-4" aria-hidden="true" tabindex="-1"></a> <span class="fu">tm_dots</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Take-home_Ex01_3_files/figure-html/unnamed-chunk-13-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
</section>
<section id="geospatial-data-wrangling" class="level2">
<h2 class="anchored" data-anchor-id="geospatial-data-wrangling"><strong>GEOSPATIAL DATA WRANGLING</strong></h2>
<p>Although simple feature data frame is gaining popularity again sp’s Spatial* classes, there are, however, many geospatial analysis packages require the input geospatial data in sp’s Spatial* classes. In this section, we will convert simple feature data frame to sp’s Spatial* class.</p>
<section id="converting-sf-data-frames-to-sps-spatial-class" class="level3">
<h3 class="anchored" data-anchor-id="converting-sf-data-frames-to-sps-spatial-class"><strong>CONVERTING SF DATA FRAMES TO SP’S SPATIAL* CLASS</strong></h3>
<p>The code chunk below uses <a href="https://r4gdsa.netlify.app/chap04.html"><em>as_Spatial()</em></a> of <strong>sf</strong> package to convert the three geospatial data from simple feature data frame to sp’s Spatial* class.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb22"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a>grab_trips <span class="ot">&lt;-</span> <span class="fu">as_Spatial</span>(trips_sf_geometry)</span>
<span id="cb22-2"><a href="#cb22-2" aria-hidden="true" tabindex="-1"></a>mpsz <span class="ot">&lt;-</span> <span class="fu">as_Spatial</span>(mpsz_sf)</span>
<span id="cb22-3"><a href="#cb22-3" aria-hidden="true" tabindex="-1"></a>sg <span class="ot">&lt;-</span> <span class="fu">as_Spatial</span>(sg_sf)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Lets view the data generated:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb23"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a>grab_trips</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>class       : SpatialPoints 
features    : 28000 
extent      : 3638.685, 50024.92, 25350.05, 49469.41  (xmin, xmax, ymin, ymax)
crs         : +proj=tmerc +lat_0=1.36666666666667 +lon_0=103.833333333333 +k=1 +x_0=28001.642 +y_0=38744.572 +ellps=WGS84 +towgs84=0,0,0,0,0,0,0 +units=m +no_defs </code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb25"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb25-1"><a href="#cb25-1" aria-hidden="true" tabindex="-1"></a>mpsz</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>class       : SpatialPolygonsDataFrame 
features    : 323 
extent      : 2667.538, 56396.44, 15748.72, 50256.33  (xmin, xmax, ymin, ymax)
crs         : +proj=tmerc +lat_0=1.36666666666667 +lon_0=103.833333333333 +k=1 +x_0=28001.642 +y_0=38744.572 +datum=WGS84 +units=m +no_defs 
variables   : 15
names       : OBJECTID, SUBZONE_NO, SUBZONE_N, SUBZONE_C, CA_IND, PLN_AREA_N, PLN_AREA_C,       REGION_N, REGION_C,          INC_CRC, FMEL_UPD_D,     X_ADDR,     Y_ADDR,    SHAPE_Leng,    SHAPE_Area 
min values  :        1,          1, ADMIRALTY,    AMSZ01,      N, ANG MO KIO,         AM, CENTRAL REGION,       CR, 00F5E30B5C9B7AD8,      16409,  5092.8949,  19579.069, 871.554887798, 39437.9352703 
max values  :      323,         17,    YUNNAN,    YSSZ09,      Y,     YISHUN,         YS,    WEST REGION,       WR, FFCCF172717C2EAF,      16409, 50424.7923, 49552.7904, 68083.9364708,  69748298.792 </code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb27"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb27-1"><a href="#cb27-1" aria-hidden="true" tabindex="-1"></a>sg</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>class       : SpatialPolygonsDataFrame 
features    : 60 
extent      : 2663.926, 56047.79, 16357.98, 50244.03  (xmin, xmax, ymin, ymax)
crs         : +proj=tmerc +lat_0=1.36666666666667 +lon_0=103.833333333333 +k=1 +x_0=28001.642 +y_0=38744.572 +datum=WGS84 +units=m +no_defs 
variables   : 4
names       : GDO_GID, MSLINK, MAPID,              COSTAL_NAM 
min values  :       1,      1,     0,             ISLAND LINK 
max values  :      60,     67,     0, SINGAPORE - MAIN ISLAND </code></pre>
</div>
</div>
</section>
<section id="converting-the-spatial-class-into-generic-sp-format" class="level3">
<h3 class="anchored" data-anchor-id="converting-the-spatial-class-into-generic-sp-format"><strong>CONVERTING THE SPATIAL* CLASS INTO GENERIC SP FORMAT</strong></h3>
<p><strong>spatstat</strong> requires the analytical data in <strong><em>ppp</em></strong> object form. There is no direct way to convert a Spatial* classes into <strong><em>ppp</em></strong> object. We need to convert the <strong><em>Spatial</em></strong> <strong>classes</strong>* into <strong><em>Spatial</em></strong> object first.</p>
<p>The codes chunk below converts the Spatial* classes into generic sp objects.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb29"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb29-1"><a href="#cb29-1" aria-hidden="true" tabindex="-1"></a>grab_trips_sp <span class="ot">&lt;-</span> <span class="fu">as</span>(grab_trips, <span class="st">"SpatialPoints"</span>)</span>
<span id="cb29-2"><a href="#cb29-2" aria-hidden="true" tabindex="-1"></a>sg_sp <span class="ot">&lt;-</span> <span class="fu">as</span>(sg, <span class="st">"SpatialPolygons"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Next, you should display the sp objects properties as shown below.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb30"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb30-1"><a href="#cb30-1" aria-hidden="true" tabindex="-1"></a>grab_trips_sp</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>class       : SpatialPoints 
features    : 28000 
extent      : 3638.685, 50024.92, 25350.05, 49469.41  (xmin, xmax, ymin, ymax)
crs         : +proj=tmerc +lat_0=1.36666666666667 +lon_0=103.833333333333 +k=1 +x_0=28001.642 +y_0=38744.572 +ellps=WGS84 +towgs84=0,0,0,0,0,0,0 +units=m +no_defs </code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb32"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb32-1"><a href="#cb32-1" aria-hidden="true" tabindex="-1"></a>sg_sp</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>class       : SpatialPolygons 
features    : 60 
extent      : 2663.926, 56047.79, 16357.98, 50244.03  (xmin, xmax, ymin, ymax)
crs         : +proj=tmerc +lat_0=1.36666666666667 +lon_0=103.833333333333 +k=1 +x_0=28001.642 +y_0=38744.572 +datum=WGS84 +units=m +no_defs </code></pre>
</div>
</div>
</section>
<section id="converting-the-generic-sp-format-into-spatstats-ppp-format" class="level3">
<h3 class="anchored" data-anchor-id="converting-the-generic-sp-format-into-spatstats-ppp-format"><strong>CONVERTING THE GENERIC SP FORMAT INTO SPATSTAT’S PPP FORMAT</strong></h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb34"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb34-1"><a href="#cb34-1" aria-hidden="true" tabindex="-1"></a>grab_trips_ppp <span class="ot">&lt;-</span> <span class="fu">as</span>(grab_trips_sp, <span class="st">"ppp"</span>)</span>
<span id="cb34-2"><a href="#cb34-2" aria-hidden="true" tabindex="-1"></a>grab_trips_ppp</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Planar point pattern: 28000 points
window: rectangle = [3638.69, 50024.92] x [25350.05, 49469.41] units</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb36"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb36-1"><a href="#cb36-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(grab_trips_ppp)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Take-home_Ex01_3_files/figure-html/unnamed-chunk-22-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb37"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb37-1"><a href="#cb37-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(grab_trips_ppp)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Planar point pattern:  28000 points
Average intensity 2.502667e-05 points per square unit

Coordinates are given to 3 decimal places
i.e. rounded to the nearest multiple of 0.001 units

Window: rectangle = [3638.69, 50024.92] x [25350.05, 49469.41] units
                    (46390 x 24120 units)
Window area = 1118810000 square units</code></pre>
</div>
</div>
</section>
<section id="handling-duplicated-points" class="level3">
<h3 class="anchored" data-anchor-id="handling-duplicated-points"><strong>HANDLING DUPLICATED POINTS</strong></h3>
<p>We can check the duplication in a <strong><em>ppp</em></strong> object by using the code chunk below.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb39"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb39-1"><a href="#cb39-1" aria-hidden="true" tabindex="-1"></a><span class="fu">any</span>(<span class="fu">duplicated</span>(grab_trips_ppp))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] FALSE</code></pre>
</div>
</div>
<p>Thus there are no duplicate data. So, we will not need to use methods to deal with duplicate data such as deleting of duplicate data, jittering and make each point “unique”.</p>
</section>
<section id="creating-owin-object" class="level3">
<h3 class="anchored" data-anchor-id="creating-owin-object"><strong>CREATING <em>OWIN</em> OBJECT</strong></h3>
<p>When analysing spatial point patterns, it is a good practice to confine the analysis with a geographical area like Singapore boundary. In <strong>spatstat</strong>, an object called <strong><em>owin</em></strong> is specially designed to represent this polygonal region.</p>
<p>The code chunk below is used to covert <em>sg</em> SpatialPolygon object into owin object of <strong>spatstat</strong>.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb41"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb41-1"><a href="#cb41-1" aria-hidden="true" tabindex="-1"></a>sg_owin <span class="ot">&lt;-</span> <span class="fu">as</span>(sg_sp, <span class="st">"owin"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>The ouput object can be displayed by using <em>plot()</em> function</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb42"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb42-1"><a href="#cb42-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(sg_owin)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Take-home_Ex01_3_files/figure-html/unnamed-chunk-26-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
</section>
<section id="combining-point-events-object-and-owin-object" class="level3">
<h3 class="anchored" data-anchor-id="combining-point-events-object-and-owin-object"><strong>COMBINING POINT EVENTS OBJECT AND OWIN OBJECT</strong></h3>
<p>In this last step of geospatial data wrangling, we will extract grab trip events that are located within Singapore by using the code chunk below.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb43"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb43-1"><a href="#cb43-1" aria-hidden="true" tabindex="-1"></a>grab_trips_ppp_SG <span class="ot">=</span> grab_trips_ppp[sg_owin]</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>The output object combined both the point and polygon feature in one ppp object class as shown below.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb44"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb44-1"><a href="#cb44-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(grab_trips_ppp_SG)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Planar point pattern:  27940 points
Average intensity 3.731596e-05 points per square unit

Coordinates are given to 3 decimal places
i.e. rounded to the nearest multiple of 0.001 units

Window: polygonal boundary
60 separate polygons (no holes)
            vertices        area relative.area
polygon 1         38 1.56140e+04      2.09e-05
polygon 2        735 4.69093e+06      6.27e-03
polygon 3         49 1.66986e+04      2.23e-05
polygon 4         76 3.12332e+05      4.17e-04
polygon 5       5141 6.36179e+08      8.50e-01
polygon 6         42 5.58317e+04      7.46e-05
polygon 7         67 1.31354e+06      1.75e-03
polygon 8         15 4.46420e+03      5.96e-06
polygon 9         14 5.46674e+03      7.30e-06
polygon 10        37 5.26194e+03      7.03e-06
polygon 11        53 3.44003e+04      4.59e-05
polygon 12        74 5.82234e+04      7.78e-05
polygon 13        69 5.63134e+04      7.52e-05
polygon 14       143 1.45139e+05      1.94e-04
polygon 15       165 3.38736e+05      4.52e-04
polygon 16       130 9.40465e+04      1.26e-04
polygon 17        19 1.80977e+03      2.42e-06
polygon 18        16 2.01046e+03      2.69e-06
polygon 19        93 4.30642e+05      5.75e-04
polygon 20        90 4.15092e+05      5.54e-04
polygon 21       721 1.92795e+06      2.57e-03
polygon 22       330 1.11896e+06      1.49e-03
polygon 23       115 9.28394e+05      1.24e-03
polygon 24        37 1.01705e+04      1.36e-05
polygon 25        25 1.66227e+04      2.22e-05
polygon 26        10 2.14507e+03      2.86e-06
polygon 27       190 2.02489e+05      2.70e-04
polygon 28       175 9.25904e+05      1.24e-03
polygon 29      1993 9.99217e+06      1.33e-02
polygon 30        38 2.42492e+04      3.24e-05
polygon 31        24 6.35239e+03      8.48e-06
polygon 32        53 6.35791e+05      8.49e-04
polygon 33        41 1.60161e+04      2.14e-05
polygon 34        22 2.54368e+03      3.40e-06
polygon 35        30 1.08382e+04      1.45e-05
polygon 36       327 2.16921e+06      2.90e-03
polygon 37       111 6.62927e+05      8.85e-04
polygon 38        90 1.15991e+05      1.55e-04
polygon 39        98 6.26829e+04      8.37e-05
polygon 40       415 3.25384e+06      4.35e-03
polygon 41       222 1.51142e+06      2.02e-03
polygon 42       107 6.33039e+05      8.45e-04
polygon 43         7 2.48299e+03      3.32e-06
polygon 44        17 3.28303e+04      4.38e-05
polygon 45        26 8.34758e+03      1.11e-05
polygon 46       177 4.67446e+05      6.24e-04
polygon 47        16 3.19460e+03      4.27e-06
polygon 48        15 4.87296e+03      6.51e-06
polygon 49        66 1.61841e+04      2.16e-05
polygon 50       149 5.63430e+06      7.53e-03
polygon 51       609 2.62570e+07      3.51e-02
polygon 52         8 7.82256e+03      1.04e-05
polygon 53       976 2.33447e+07      3.12e-02
polygon 54        55 8.25379e+04      1.10e-04
polygon 55       976 2.33447e+07      3.12e-02
polygon 56        61 3.33449e+05      4.45e-04
polygon 57         6 1.68410e+04      2.25e-05
polygon 58         4 9.45963e+03      1.26e-05
polygon 59        46 6.99702e+05      9.35e-04
polygon 60        13 7.00873e+04      9.36e-05
enclosing rectangle: [2663.93, 56047.79] x [16357.98, 50244.03] units
                     (53380 x 33890 units)
Window area = 748741000 square units
Fraction of frame area: 0.414</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb46"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb46-1"><a href="#cb46-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(grab_trips_ppp_SG)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Take-home_Ex01_3_files/figure-html/unnamed-chunk-29-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
</section>
</section>
<section id="first-order-spatial-point-patterns-analysis" class="level2">
<h2 class="anchored" data-anchor-id="first-order-spatial-point-patterns-analysis"><strong>FIRST-ORDER SPATIAL POINT PATTERNS ANALYSIS</strong></h2>
<p>In this section, we will perform first-order SPPA by using <strong>spatstat</strong> package. The hands-on exercise will focus on:</p>
<ul>
<li><p>deriving <strong>kernel density estimation (KDE)</strong> layer for visualising and exploring the intensity of point processes,</p></li>
<li><p>performing <strong>Confirmatory Spatial Point Patterns Analysis</strong> by using <strong>Nearest Neighbour</strong> statistics.</p></li>
</ul>
<section id="kernel-density-estimation" class="level3">
<h3 class="anchored" data-anchor-id="kernel-density-estimation"><strong>KERNEL DENSITY ESTIMATION</strong></h3>
<p>In this section, we will compute the kernel density estimation (KDE) of grab trips in Singapore.</p>
<section id="computing-kernel-density-estimation-using-automatic-bandwidth-selection-method" class="level4">
<h4 class="anchored" data-anchor-id="computing-kernel-density-estimation-using-automatic-bandwidth-selection-method"><strong>COMPUTING KERNEL DENSITY ESTIMATION USING AUTOMATIC BANDWIDTH SELECTION METHOD</strong></h4>
<p>The code chunk below computes a kernel density by using the following configurations of <a href="https://rdrr.io/cran/spatstat/man/density.ppp.html"><em>density()</em></a> of <strong>spatstat</strong>:</p>
<ul>
<li><p><a href="https://rdrr.io/cran/spatstat/man/bw.diggle.html"><em>bw.diggle()</em></a> automatic bandwidth selection method. Other recommended methods are <a href="https://rdrr.io/cran/spatstat/man/bw.CvL.html"><em>bw.CvL()</em></a>, <a href="https://rdrr.io/cran/spatstat/man/bw.scott.html"><em>bw.scott()</em></a> or <a href="https://rdrr.io/cran/spatstat/man/bw.ppl.html"><em>bw.ppl()</em></a>.</p></li>
<li><p>The smoothing kernel used is <em>gaussian</em>, which is the default. Other smoothing methods are: “epanechnikov”, “quartic” or “disc”.</p></li>
<li><p>The intensity estimate is corrected for edge effect bias by using method described by Jones (1993) and Diggle (2010, equation 18.9). The default is <em>FALSE</em>.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb47"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb47-1"><a href="#cb47-1" aria-hidden="true" tabindex="-1"></a>kde_grab_trips_SG_bw <span class="ot">&lt;-</span> <span class="fu">density</span>(grab_trips_ppp_SG,</span>
<span id="cb47-2"><a href="#cb47-2" aria-hidden="true" tabindex="-1"></a>                              <span class="at">sigma=</span>bw.diggle,</span>
<span id="cb47-3"><a href="#cb47-3" aria-hidden="true" tabindex="-1"></a>                              <span class="at">edge=</span><span class="cn">TRUE</span>,</span>
<span id="cb47-4"><a href="#cb47-4" aria-hidden="true" tabindex="-1"></a>                            <span class="at">kernel=</span><span class="st">"gaussian"</span>) </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div></li>
</ul>
<p>The <em>plot()</em> function of Base R is then used to display the kernel density derived.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb48"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb48-1"><a href="#cb48-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(kde_grab_trips_SG_bw)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Take-home_Ex01_3_files/figure-html/unnamed-chunk-31-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>The density values of the output range from 0 to 0.000035 which is way too small to comprehend. This is because the default unit of measurement of svy21 is in meter. As a result, the density values computed is in “number of points per square meter”.</p>
<p>Before we move on to next section, it is good to know that you can retrieve the bandwidth used to compute the kde layer by using the code chunk below.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb49"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb49-1"><a href="#cb49-1" aria-hidden="true" tabindex="-1"></a>bw <span class="ot">&lt;-</span> <span class="fu">bw.diggle</span>(grab_trips_ppp_SG)</span>
<span id="cb49-2"><a href="#cb49-2" aria-hidden="true" tabindex="-1"></a>bw</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>   sigma 
11.43107 </code></pre>
</div>
</div>
</section>
<section id="rescalling-kde-values---leads-to-better-visualisation" class="level4">
<h4 class="anchored" data-anchor-id="rescalling-kde-values---leads-to-better-visualisation"><strong>RESCALLING KDE VALUES - Leads to better visualisation</strong></h4>
<p>In the code chunk below, <em>rescale()</em> is used to covert the unit of measurement from meter to kilometer.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb51"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb51-1"><a href="#cb51-1" aria-hidden="true" tabindex="-1"></a>grab_trips_ppp_SG.km <span class="ot">&lt;-</span> <span class="fu">rescale</span>(grab_trips_ppp_SG, <span class="dv">1000</span>, <span class="st">"km"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Now, we can re-run <em>density()</em> using the resale data set and plot the output kde map.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb52"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb52-1"><a href="#cb52-1" aria-hidden="true" tabindex="-1"></a>kde_grab_trips_SG.bw <span class="ot">&lt;-</span> <span class="fu">density</span>(grab_trips_ppp_SG.km, <span class="at">sigma=</span>bw.diggle, <span class="at">edge=</span><span class="cn">TRUE</span>, <span class="at">kernel=</span><span class="st">"gaussian"</span>)</span>
<span id="cb52-2"><a href="#cb52-2" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(kde_grab_trips_SG.bw)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Take-home_Ex01_3_files/figure-html/unnamed-chunk-34-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
</section>
</section>
<section id="working-with-different-automatic-badwidth-methods" class="level3">
<h3 class="anchored" data-anchor-id="working-with-different-automatic-badwidth-methods"><strong>WORKING WITH DIFFERENT AUTOMATIC BADWIDTH METHODS</strong></h3>
<p>Beside <em>bw.diggle()</em>, there are three other <strong>spatstat</strong> functions can be used to determine the bandwidth, they are: <em>bw.CvL()</em>, <em>bw.scott()</em>, and <em>bw.ppl()</em>.</p>
<p>Let us take a look at the bandwidth return by these automatic bandwidth calculation methods by using the code chunk below.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb53"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb53-1"><a href="#cb53-1" aria-hidden="true" tabindex="-1"></a> <span class="fu">bw.CvL</span>(grab_trips_ppp_SG.km)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>   sigma 
3.032202 </code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb55"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb55-1"><a href="#cb55-1" aria-hidden="true" tabindex="-1"></a><span class="fu">bw.scott</span>(grab_trips_ppp_SG.km)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>  sigma.x   sigma.y 
1.4712700 0.9005008 </code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb57"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb57-1"><a href="#cb57-1" aria-hidden="true" tabindex="-1"></a><span class="fu">bw.ppl</span>(grab_trips_ppp_SG.km)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>    sigma 
0.3207578 </code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb59"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb59-1"><a href="#cb59-1" aria-hidden="true" tabindex="-1"></a><span class="fu">bw.diggle</span>(grab_trips_ppp_SG.km)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>     sigma 
0.01143107 </code></pre>
</div>
</div>
<p>Baddeley et. (2016) suggested the use of the <em>bw.ppl()</em> algorithm because in ther experience it tends to produce the more appropriate values when the pattern consists predominantly of tight clusters. But they also insist that if the purpose of once study is to detect a single tight cluster in the midst of random noise then the <em>bw.diggle()</em> method seems to work best.</p>
<p>The code chunk beow will be used to compare the output of using <em>bw.diggle</em> and <em>bw.ppl</em> methods.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb61"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb61-1"><a href="#cb61-1" aria-hidden="true" tabindex="-1"></a>kde_grab_trips_SG.ppl <span class="ot">&lt;-</span> <span class="fu">density</span>(grab_trips_ppp_SG.km, </span>
<span id="cb61-2"><a href="#cb61-2" aria-hidden="true" tabindex="-1"></a>                               <span class="at">sigma=</span>bw.ppl, </span>
<span id="cb61-3"><a href="#cb61-3" aria-hidden="true" tabindex="-1"></a>                               <span class="at">edge=</span><span class="cn">TRUE</span>,</span>
<span id="cb61-4"><a href="#cb61-4" aria-hidden="true" tabindex="-1"></a>                               <span class="at">kernel=</span><span class="st">"gaussian"</span>)</span>
<span id="cb61-5"><a href="#cb61-5" aria-hidden="true" tabindex="-1"></a><span class="fu">par</span>(<span class="at">mfrow=</span><span class="fu">c</span>(<span class="dv">1</span>,<span class="dv">2</span>))</span>
<span id="cb61-6"><a href="#cb61-6" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(kde_grab_trips_SG.bw, <span class="at">main =</span> <span class="st">"bw.diggle"</span>)</span>
<span id="cb61-7"><a href="#cb61-7" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(kde_grab_trips_SG.ppl, <span class="at">main =</span> <span class="st">"bw.ppl"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Take-home_Ex01_3_files/figure-html/unnamed-chunk-39-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
</section>
<section id="working-with-different-kernel-methods" class="level3">
<h3 class="anchored" data-anchor-id="working-with-different-kernel-methods">WORKING WITH DIFFERENT KERNEL METHODS</h3>
<p>By default, the kernel method used in density.ppp() is gaussian. But there are three other options, namely: Epanechnikov, Quartic and Dics.The code chunk below will be used to compute three more kernel density estimations by using these three kernel function.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb62"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb62-1"><a href="#cb62-1" aria-hidden="true" tabindex="-1"></a><span class="fu">par</span>(<span class="at">mfrow=</span><span class="fu">c</span>(<span class="dv">2</span>,<span class="dv">2</span>))</span>
<span id="cb62-2"><a href="#cb62-2" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(<span class="fu">density</span>(grab_trips_ppp_SG.km, </span>
<span id="cb62-3"><a href="#cb62-3" aria-hidden="true" tabindex="-1"></a>             <span class="at">sigma=</span>bw.ppl, </span>
<span id="cb62-4"><a href="#cb62-4" aria-hidden="true" tabindex="-1"></a>             <span class="at">edge=</span><span class="cn">TRUE</span>, </span>
<span id="cb62-5"><a href="#cb62-5" aria-hidden="true" tabindex="-1"></a>             <span class="at">kernel=</span><span class="st">"gaussian"</span>), </span>
<span id="cb62-6"><a href="#cb62-6" aria-hidden="true" tabindex="-1"></a>     <span class="at">main=</span><span class="st">"Gaussian"</span>)</span>
<span id="cb62-7"><a href="#cb62-7" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(<span class="fu">density</span>(grab_trips_ppp_SG.km, </span>
<span id="cb62-8"><a href="#cb62-8" aria-hidden="true" tabindex="-1"></a>             <span class="at">sigma=</span>bw.ppl, </span>
<span id="cb62-9"><a href="#cb62-9" aria-hidden="true" tabindex="-1"></a>             <span class="at">edge=</span><span class="cn">TRUE</span>, </span>
<span id="cb62-10"><a href="#cb62-10" aria-hidden="true" tabindex="-1"></a>             <span class="at">kernel=</span><span class="st">"epanechnikov"</span>), </span>
<span id="cb62-11"><a href="#cb62-11" aria-hidden="true" tabindex="-1"></a>     <span class="at">main=</span><span class="st">"Epanechnikov"</span>)</span>
<span id="cb62-12"><a href="#cb62-12" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(<span class="fu">density</span>(grab_trips_ppp_SG.km, </span>
<span id="cb62-13"><a href="#cb62-13" aria-hidden="true" tabindex="-1"></a>             <span class="at">sigma=</span>bw.ppl, </span>
<span id="cb62-14"><a href="#cb62-14" aria-hidden="true" tabindex="-1"></a>             <span class="at">edge=</span><span class="cn">TRUE</span>, </span>
<span id="cb62-15"><a href="#cb62-15" aria-hidden="true" tabindex="-1"></a>             <span class="at">kernel=</span><span class="st">"quartic"</span>), </span>
<span id="cb62-16"><a href="#cb62-16" aria-hidden="true" tabindex="-1"></a>     <span class="at">main=</span><span class="st">"Quartic"</span>)</span>
<span id="cb62-17"><a href="#cb62-17" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(<span class="fu">density</span>(grab_trips_ppp_SG.km, </span>
<span id="cb62-18"><a href="#cb62-18" aria-hidden="true" tabindex="-1"></a>             <span class="at">sigma=</span>bw.ppl, </span>
<span id="cb62-19"><a href="#cb62-19" aria-hidden="true" tabindex="-1"></a>             <span class="at">edge=</span><span class="cn">TRUE</span>, </span>
<span id="cb62-20"><a href="#cb62-20" aria-hidden="true" tabindex="-1"></a>             <span class="at">kernel=</span><span class="st">"disc"</span>), </span>
<span id="cb62-21"><a href="#cb62-21" aria-hidden="true" tabindex="-1"></a>     <span class="at">main=</span><span class="st">"Disc"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Take-home_Ex01_3_files/figure-html/unnamed-chunk-40-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
</section>
</section>
<section id="fixed-and-adaptive-kde" class="level2">
<h2 class="anchored" data-anchor-id="fixed-and-adaptive-kde"><strong>FIXED AND ADAPTIVE KDE</strong></h2>
<section id="computing-kde-by-using-fixed-bandwidth" class="level3">
<h3 class="anchored" data-anchor-id="computing-kde-by-using-fixed-bandwidth"><strong>COMPUTING KDE BY USING FIXED BANDWIDTH</strong></h3>
<p>Next, you will compute a KDE layer by defining a bandwidth of 600 meter. Notice that in the code chunk below, the sigma value used is 0.6. This is because the unit of measurement of grab_trips_ppp_SG.km object is in kilometer, hence the 600m is 0.6km.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb63"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb63-1"><a href="#cb63-1" aria-hidden="true" tabindex="-1"></a>kde_grab_trips_600 <span class="ot">&lt;-</span> <span class="fu">density</span>(grab_trips_ppp_SG.km, <span class="at">sigma=</span><span class="fl">0.6</span>, <span class="at">edge=</span><span class="cn">TRUE</span>, <span class="at">kernel=</span><span class="st">"gaussian"</span>)</span>
<span id="cb63-2"><a href="#cb63-2" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(kde_grab_trips_600)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Take-home_Ex01_3_files/figure-html/unnamed-chunk-41-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
</section>
<section id="computing-kde-by-using-adaptive-bandwidth" class="level3">
<h3 class="anchored" data-anchor-id="computing-kde-by-using-adaptive-bandwidth"><strong>COMPUTING KDE BY USING ADAPTIVE BANDWIDTH</strong></h3>
<p>Fixed bandwidth method is very sensitive to highly skew distribution of spatial point patterns over geographical units for example urban versus rural. One way to overcome this problem is by using adaptive bandwidth instead. However, since in Singapore, it is a small city with fully urban zones, adaptive bandwidth will be unnecessary and fixed bandwidth will be more suitable. However, we will experiment and display both to see the difference.</p>
<p>In this section, we will derive adaptive kernel density estimation by using <a href="https://rdrr.io/cran/spatstat/man/adaptive.density.html"><em>density.adaptive()</em></a> of <strong>spatstat</strong>.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb64"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb64-1"><a href="#cb64-1" aria-hidden="true" tabindex="-1"></a>kde_grabtripssg_adaptive <span class="ot">&lt;-</span> <span class="fu">adaptive.density</span>(grab_trips_ppp_SG.km, <span class="at">method=</span><span class="st">"kernel"</span>)</span>
<span id="cb64-2"><a href="#cb64-2" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(kde_grabtripssg_adaptive)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Take-home_Ex01_3_files/figure-html/unnamed-chunk-42-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>We can compare the fixed and adaptive kernel density estimation outputs by using the code chunk below.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb65"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb65-1"><a href="#cb65-1" aria-hidden="true" tabindex="-1"></a><span class="fu">par</span>(<span class="at">mfrow=</span><span class="fu">c</span>(<span class="dv">1</span>,<span class="dv">2</span>))</span>
<span id="cb65-2"><a href="#cb65-2" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(kde_grab_trips_SG.bw, <span class="at">main =</span> <span class="st">"Fixed bandwidth"</span>)</span>
<span id="cb65-3"><a href="#cb65-3" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(kde_grabtripssg_adaptive, <span class="at">main =</span> <span class="st">"Adaptive bandwidth"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Take-home_Ex01_3_files/figure-html/unnamed-chunk-43-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
</section>
<section id="converting-kde-output-into-grid-object." class="level3">
<h3 class="anchored" data-anchor-id="converting-kde-output-into-grid-object."><strong>CONVERTING KDE OUTPUT INTO GRID OBJECT.</strong></h3>
<p>The result is the same, we just convert it so that it is suitable for mapping purposes</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb66"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb66-1"><a href="#cb66-1" aria-hidden="true" tabindex="-1"></a>gridded_kde_grabtripsSG_bw <span class="ot">&lt;-</span> <span class="fu">as.SpatialGridDataFrame.im</span>(kde_grab_trips_SG.bw)</span>
<span id="cb66-2"><a href="#cb66-2" aria-hidden="true" tabindex="-1"></a><span class="fu">spplot</span>(gridded_kde_grabtripsSG_bw)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Take-home_Ex01_3_files/figure-html/unnamed-chunk-44-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>As can be seen above, the highest trip destinations occur in central area and east area near Changi. We may assume many people going to the airport may be rushing there with their large luggages using ride hailing services. Thus, there is a lot of grab trips with their destinations being at Changi airport area.</p>
<section id="converting-gridded-output-into-raster" class="level4">
<h4 class="anchored" data-anchor-id="converting-gridded-output-into-raster"><strong>CONVERTING GRIDDED OUTPUT INTO RASTER</strong></h4>
<p>Next, we will convert the gridded kernal density objects into RasterLayer object by using <em>raster()</em> of <strong>raster</strong> package.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb67"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb67-1"><a href="#cb67-1" aria-hidden="true" tabindex="-1"></a>kde_grabtrips_bw_raster <span class="ot">&lt;-</span> <span class="fu">raster</span>(gridded_kde_grabtripsSG_bw)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Let us take a look at the properties of kde_grabtrips_bw_raster RasterLayer.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb68"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb68-1"><a href="#cb68-1" aria-hidden="true" tabindex="-1"></a>kde_grabtrips_bw_raster</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>class      : RasterLayer 
dimensions : 128, 128, 16384  (nrow, ncol, ncell)
resolution : 0.4170614, 0.2647348  (x, y)
extent     : 2.663926, 56.04779, 16.35798, 50.24403  (xmin, xmax, ymin, ymax)
crs        : NA 
source     : memory
names      : v 
values     : -4.082491e-13, 2010.675  (min, max)</code></pre>
</div>
</div>
<pre><code>class      : RasterLayer 
dimensions : 128, 128, 16384  (nrow, ncol, ncell)
resolution : 0.4170614, 0.2647348  (x, y)
extent     : 2.663926, 56.04779, 16.35798, 50.24403  (xmin, xmax, ymin, ymax)
crs        : NA 
source     : memory
names      : v 
values     : -6.837601e-15, 32.45281  (min, max)</code></pre>
<p>Notice that the crs property is NA.</p>
</section>
<section id="assigning-projection-systems" class="level4">
<h4 class="anchored" data-anchor-id="assigning-projection-systems"><strong>ASSIGNING PROJECTION SYSTEMS</strong></h4>
<p>The code chunk below will be used to include the CRS information on gridded_kde_grabtripsSG_bw RasterLayer. It has been projected to Singapore’s coordinate system using 3414.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb71"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb71-1"><a href="#cb71-1" aria-hidden="true" tabindex="-1"></a><span class="fu">projection</span>(kde_grabtrips_bw_raster) <span class="ot">&lt;-</span> <span class="fu">CRS</span>(<span class="st">"+init=EPSG:3414"</span>)</span>
<span id="cb71-2"><a href="#cb71-2" aria-hidden="true" tabindex="-1"></a>kde_grabtrips_bw_raster</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>class      : RasterLayer 
dimensions : 128, 128, 16384  (nrow, ncol, ncell)
resolution : 0.4170614, 0.2647348  (x, y)
extent     : 2.663926, 56.04779, 16.35798, 50.24403  (xmin, xmax, ymin, ymax)
crs        : +proj=tmerc +lat_0=1.36666666666667 +lon_0=103.833333333333 +k=1 +x_0=28001.642 +y_0=38744.572 +ellps=WGS84 +units=m +no_defs 
source     : memory
names      : v 
values     : -4.082491e-13, 2010.675  (min, max)</code></pre>
</div>
</div>
<pre><code>class      : RasterLayer 
dimensions : 128, 128, 16384  (nrow, ncol, ncell)
resolution : 0.4170614, 0.2647348  (x, y)
extent     : 2.663926, 56.04779, 16.35798, 50.24403  (xmin, xmax, ymin, ymax)
crs        : +proj=tmerc +lat_0=1.36666666666667 +lon_0=103.833333333333 +k=1 +x_0=28001.642 +y_0=38744.572 +ellps=WGS84 +units=m +no_defs 
source     : memory
names      : v 
values     : -6.837601e-15, 32.45281  (min, max)</code></pre>
<p>Notice that the crs property is completed.</p>
</section>
</section>
<section id="visualising-the-output-in-tmap" class="level3">
<h3 class="anchored" data-anchor-id="visualising-the-output-in-tmap"><strong>VISUALISING THE OUTPUT IN TMAP</strong></h3>
<p>Finally, we will display the raster in cartographic quality map using <strong>tmap</strong> package.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb74"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb74-1"><a href="#cb74-1" aria-hidden="true" tabindex="-1"></a><span class="fu">tm_shape</span>(kde_grabtrips_bw_raster) <span class="sc">+</span> </span>
<span id="cb74-2"><a href="#cb74-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tm_raster</span>(<span class="st">"v"</span>) <span class="sc">+</span></span>
<span id="cb74-3"><a href="#cb74-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tm_layout</span>(<span class="at">legend.position =</span> <span class="fu">c</span>(<span class="st">"right"</span>, <span class="st">"bottom"</span>), <span class="at">frame =</span> <span class="cn">FALSE</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Take-home_Ex01_3_files/figure-html/unnamed-chunk-48-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Clearly, the number of trips to changi airport region is clearly in the 2000 - 2500 range. This gives a very skewed distribution for this range in certain parts of the map.</p>
</section>
<section id="comparing-spatial-point-patterns-using-kde" class="level3">
<h3 class="anchored" data-anchor-id="comparing-spatial-point-patterns-using-kde"><strong>COMPARING SPATIAL POINT PATTERNS USING KDE</strong></h3>
<p>In this section, you will learn how to compare KDE of grab trip destinations at Ponggol, Tampines, Chua Chu Kang and Jurong West planning areas.</p>
<section id="extracting-study-area" class="level4">
<h4 class="anchored" data-anchor-id="extracting-study-area"><strong>EXTRACTING STUDY AREA</strong></h4>
<p>The code chunk below will be used to extract the target planning areas.</p>
<p>Lets view all available zones to zoom it on:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb75"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb75-1"><a href="#cb75-1" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(mpsz<span class="sc">@</span>data<span class="sc">$</span>PLN_AREA_N)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>  [1] "MARINA SOUTH"            "OUTRAM"                 
  [3] "SINGAPORE RIVER"         "BUKIT MERAH"            
  [5] "BUKIT MERAH"             "BUKIT MERAH"            
  [7] "BUKIT MERAH"             "SINGAPORE RIVER"        
  [9] "QUEENSTOWN"              "QUEENSTOWN"             
 [11] "QUEENSTOWN"              "BUKIT MERAH"            
 [13] "MARINA EAST"             "RIVER VALLEY"           
 [15] "SINGAPORE RIVER"         "WESTERN ISLANDS"        
 [17] "WESTERN ISLANDS"         "WESTERN ISLANDS"        
 [19] "SOUTHERN ISLANDS"        "SOUTHERN ISLANDS"       
 [21] "BUKIT MERAH"             "DOWNTOWN CORE"          
 [23] "STRAITS VIEW"            "BUKIT MERAH"            
 [25] "BUKIT MERAH"             "DOWNTOWN CORE"          
 [27] "DOWNTOWN CORE"           "BUKIT MERAH"            
 [29] "BUKIT MERAH"             "QUEENSTOWN"             
 [31] "DOWNTOWN CORE"           "BUKIT MERAH"            
 [33] "BUKIT MERAH"             "OUTRAM"                 
 [35] "BUKIT MERAH"             "OUTRAM"                 
 [37] "DOWNTOWN CORE"           "DOWNTOWN CORE"          
 [39] "OUTRAM"                  "BUKIT MERAH"            
 [41] "DOWNTOWN CORE"           "BUKIT MERAH"            
 [43] "DOWNTOWN CORE"           "MARINE PARADE"          
 [45] "DOWNTOWN CORE"           "MUSEUM"                 
 [47] "RIVER VALLEY"            "DOWNTOWN CORE"          
 [49] "QUEENSTOWN"              "MARINE PARADE"          
 [51] "QUEENSTOWN"              "RIVER VALLEY"           
 [53] "ORCHARD"                 "ROCHOR"                 
 [55] "RIVER VALLEY"            "QUEENSTOWN"             
 [57] "MUSEUM"                  "DOWNTOWN CORE"          
 [59] "ROCHOR"                  "RIVER VALLEY"           
 [61] "BUKIT MERAH"             "DOWNTOWN CORE"          
 [63] "BUKIT MERAH"             "QUEENSTOWN"             
 [65] "ROCHOR"                  "ROCHOR"                 
 [67] "QUEENSTOWN"              "KALLANG"                
 [69] "MARINE PARADE"           "QUEENSTOWN"             
 [71] "QUEENSTOWN"              "TANGLIN"                
 [73] "NEWTON"                  "CLEMENTI"               
 [75] "TUAS"                    "NEWTON"                 
 [77] "BEDOK"                   "CLEMENTI"               
 [79] "PIONEER"                 "JURONG EAST"            
 [81] "NEWTON"                  "KALLANG"                
 [83] "ORCHARD"                 "NEWTON"                 
 [85] "ROCHOR"                  "PIONEER"                
 [87] "MUSEUM"                  "BUKIT TIMAH"            
 [89] "TUAS"                    "TANGLIN"                
 [91] "CLEMENTI"                "BEDOK"                  
 [93] "PIONEER"                 "PIONEER"                
 [95] "TANGLIN"                 "ROCHOR"                 
 [97] "ROCHOR"                  "ROCHOR"                 
 [99] "ROCHOR"                  "KALLANG"                
[101] "QUEENSTOWN"              "ORCHARD"                
[103] "MARINE PARADE"           "JURONG EAST"            
[105] "KALLANG"                 "CLEMENTI"               
[107] "NOVENA"                  "BEDOK"                  
[109] "KALLANG"                 "NOVENA"                 
[111] "TUAS"                    "PIONEER"                
[113] "GEYLANG"                 "JURONG EAST"            
[115] "BOON LAY"                "BUKIT TIMAH"            
[117] "BEDOK"                   "MARINE PARADE"          
[119] "QUEENSTOWN"              "ROCHOR"                 
[121] "NEWTON"                  "JURONG EAST"            
[123] "BOON LAY"                "BOON LAY"               
[125] "QUEENSTOWN"              "KALLANG"                
[127] "NEWTON"                  "CLEMENTI"               
[129] "QUEENSTOWN"              "CLEMENTI"               
[131] "KALLANG"                 "KALLANG"                
[133] "KALLANG"                 "BUKIT TIMAH"            
[135] "JURONG EAST"             "BUKIT TIMAH"            
[137] "GEYLANG"                 "TOA PAYOH"              
[139] "TOA PAYOH"               "TUAS"                   
[141] "TOA PAYOH"               "TOA PAYOH"              
[143] "JURONG WEST"             "JURONG WEST"            
[145] "TOA PAYOH"               "JURONG WEST"            
[147] "JURONG EAST"             "TOA PAYOH"              
[149] "BEDOK"                   "JURONG EAST"            
[151] "BUKIT BATOK"             "JURONG WEST"            
[153] "BEDOK"                   "CLEMENTI"               
[155] "NOVENA"                  "BUKIT TIMAH"            
[157] "TOA PAYOH"               "JURONG WEST"            
[159] "TOA PAYOH"               "JURONG EAST"            
[161] "TOA PAYOH"               "TOA PAYOH"              
[163] "GEYLANG"                 "TANGLIN"                
[165] "NOVENA"                  "BOON LAY"               
[167] "BEDOK"                   "CLEMENTI"               
[169] "BUKIT TIMAH"             "GEYLANG"                
[171] "JURONG EAST"             "JURONG WEST"            
[173] "BUKIT BATOK"             "BUKIT BATOK"            
[175] "BUKIT BATOK"             "SERANGOON"              
[177] "JURONG WEST"             "TUAS"                   
[179] "PAYA LEBAR"              "SERANGOON"              
[181] "BISHAN"                  "TAMPINES"               
[183] "BUKIT BATOK"             "HOUGANG"                
[185] "BUKIT BATOK"             "BISHAN"                 
[187] "JURONG WEST"             "BUKIT PANJANG"          
[189] "TAMPINES"                "HOUGANG"                
[191] "TUAS"                    "JURONG EAST"            
[193] "JURONG WEST"             "SERANGOON"              
[195] "NOVENA"                  "CLEMENTI"               
[197] "GEYLANG"                 "TOA PAYOH"              
[199] "BEDOK"                   "TOA PAYOH"              
[201] "PAYA LEBAR"              "HOUGANG"                
[203] "HOUGANG"                 "HOUGANG"                
[205] "ANG MO KIO"              "BUKIT PANJANG"          
[207] "CHOA CHU KANG"           "HOUGANG"                
[209] "PAYA LEBAR"              "BUKIT PANJANG"          
[211] "BUKIT TIMAH"             "BUKIT TIMAH"            
[213] "TAMPINES"                "TAMPINES"               
[215] "CHOA CHU KANG"           "PASIR RIS"              
[217] "ANG MO KIO"              "HOUGANG"                
[219] "CHOA CHU KANG"           "CHOA CHU KANG"          
[221] "CHANGI"                  "BUKIT PANJANG"          
[223] "BUKIT PANJANG"           "BUKIT PANJANG"          
[225] "SERANGOON"               "SENGKANG"               
[227] "ANG MO KIO"              "ANG MO KIO"             
[229] "PASIR RIS"               "ANG MO KIO"             
[231] "HOUGANG"                 "PASIR RIS"              
[233] "BUKIT BATOK"             "CHANGI BAY"             
[235] "PAYA LEBAR"              "BISHAN"                 
[237] "BUKIT BATOK"             "ANG MO KIO"             
[239] "HOUGANG"                 "ANG MO KIO"             
[241] "ANG MO KIO"              "SERANGOON"              
[243] "HOUGANG"                 "PASIR RIS"              
[245] "BUKIT PANJANG"           "PASIR RIS"              
[247] "TAMPINES"                "ANG MO KIO"             
[249] "ANG MO KIO"              "ANG MO KIO"             
[251] "SERANGOON"               "TENGAH"                 
[253] "SERANGOON"               "PASIR RIS"              
[255] "BUKIT BATOK"             "PAYA LEBAR"             
[257] "SUNGEI KADUT"            "PASIR RIS"              
[259] "CHOA CHU KANG"           "SENGKANG"               
[261] "SENGKANG"                "SENGKANG"               
[263] "PUNGGOL"                 "CHOA CHU KANG"          
[265] "PASIR RIS"               "PUNGGOL"                
[267] "PUNGGOL"                 "SUNGEI KADUT"           
[269] "CHANGI"                  "ANG MO KIO"             
[271] "CHANGI"                  "SENGKANG"               
[273] "SENGKANG"                "SENGKANG"               
[275] "YISHUN"                  "YISHUN"                 
[277] "PUNGGOL"                 "MANDAI"                 
[279] "YISHUN"                  "SELETAR"                
[281] "SUNGEI KADUT"            "WOODLANDS"              
[283] "WOODLANDS"               "YISHUN"                 
[285] "WESTERN WATER CATCHMENT" "SELETAR"                
[287] "YISHUN"                  "WOODLANDS"              
[289] "SUNGEI KADUT"            "WOODLANDS"              
[291] "SEMBAWANG"               "WOODLANDS"              
[293] "SEMBAWANG"               "WOODLANDS"              
[295] "SIMPANG"                 "SEMBAWANG"              
[297] "LIM CHU KANG"            "SIMPANG"                
[299] "SEMBAWANG"               "SEMBAWANG"              
[301] "SIMPANG"                 "NORTH-EASTERN ISLANDS"  
[303] "MANDAI"                  "SIMPANG"                
[305] "YISHUN"                  "WOODLANDS"              
[307] "WOODLANDS"               "SEMBAWANG"              
[309] "YISHUN"                  "PUNGGOL"                
[311] "YISHUN"                  "PUNGGOL"                
[313] "CENTRAL WATER CATCHMENT" "SELETAR"                
[315] "SUNGEI KADUT"            "SELETAR"                
[317] "YISHUN"                  "MANDAI"                 
[319] "PUNGGOL"                 "WOODLANDS"              
[321] "SEMBAWANG"               "SEMBAWANG"              
[323] "SEMBAWANG"              </code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb77"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb77-1"><a href="#cb77-1" aria-hidden="true" tabindex="-1"></a>pg <span class="ot">=</span> mpsz[mpsz<span class="sc">@</span>data<span class="sc">$</span>PLN_AREA_N <span class="sc">==</span> <span class="st">"CHANGI"</span>,]</span>
<span id="cb77-2"><a href="#cb77-2" aria-hidden="true" tabindex="-1"></a>tm <span class="ot">=</span> mpsz[mpsz<span class="sc">@</span>data<span class="sc">$</span>PLN_AREA_N <span class="sc">==</span> <span class="st">"MARINE PARADE"</span>,]</span>
<span id="cb77-3"><a href="#cb77-3" aria-hidden="true" tabindex="-1"></a>ck <span class="ot">=</span> mpsz[mpsz<span class="sc">@</span>data<span class="sc">$</span>PLN_AREA_N <span class="sc">==</span> <span class="st">"CHOA CHU KANG"</span>,]</span>
<span id="cb77-4"><a href="#cb77-4" aria-hidden="true" tabindex="-1"></a>jw <span class="ot">=</span> mpsz[mpsz<span class="sc">@</span>data<span class="sc">$</span>PLN_AREA_N <span class="sc">==</span> <span class="st">"JURONG WEST"</span>,]</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Plotting target planning areas</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb78"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb78-1"><a href="#cb78-1" aria-hidden="true" tabindex="-1"></a><span class="fu">par</span>(<span class="at">mfrow=</span><span class="fu">c</span>(<span class="dv">2</span>,<span class="dv">2</span>))</span>
<span id="cb78-2"><a href="#cb78-2" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(pg, <span class="at">main =</span> <span class="st">"Changi"</span>)</span>
<span id="cb78-3"><a href="#cb78-3" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(tm, <span class="at">main =</span> <span class="st">"Marine Parade"</span>)</span>
<span id="cb78-4"><a href="#cb78-4" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(ck, <span class="at">main =</span> <span class="st">"Choa Chu Kang"</span>)</span>
<span id="cb78-5"><a href="#cb78-5" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(jw, <span class="at">main =</span> <span class="st">"Jurong West"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Take-home_Ex01_3_files/figure-html/unnamed-chunk-51-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
</section>
<section id="converting-the-spatial-point-data-frame-into-generic-sp-format" class="level4">
<h4 class="anchored" data-anchor-id="converting-the-spatial-point-data-frame-into-generic-sp-format"><strong>CONVERTING THE SPATIAL POINT DATA FRAME INTO GENERIC SP FORMAT</strong></h4>
<p>Next, we will convert these SpatialPolygonsDataFrame layers into generic spatialpolygons layers.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb79"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb79-1"><a href="#cb79-1" aria-hidden="true" tabindex="-1"></a>pg_sp <span class="ot">=</span> <span class="fu">as</span>(pg, <span class="st">"SpatialPolygons"</span>)</span>
<span id="cb79-2"><a href="#cb79-2" aria-hidden="true" tabindex="-1"></a>tm_sp <span class="ot">=</span> <span class="fu">as</span>(tm, <span class="st">"SpatialPolygons"</span>)</span>
<span id="cb79-3"><a href="#cb79-3" aria-hidden="true" tabindex="-1"></a>ck_sp <span class="ot">=</span> <span class="fu">as</span>(ck, <span class="st">"SpatialPolygons"</span>)</span>
<span id="cb79-4"><a href="#cb79-4" aria-hidden="true" tabindex="-1"></a>jw_sp <span class="ot">=</span> <span class="fu">as</span>(jw, <span class="st">"SpatialPolygons"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="creating-owin-object-1" class="level4">
<h4 class="anchored" data-anchor-id="creating-owin-object-1"><strong>CREATING <em>OWIN</em> OBJECT</strong></h4>
<p>Now, we will convert these SpatialPolygons objects into owin objects that is required by <strong>spatstat</strong>.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb80"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb80-1"><a href="#cb80-1" aria-hidden="true" tabindex="-1"></a>pg_owin <span class="ot">=</span> <span class="fu">as</span>(pg_sp, <span class="st">"owin"</span>)</span>
<span id="cb80-2"><a href="#cb80-2" aria-hidden="true" tabindex="-1"></a>tm_owin <span class="ot">=</span> <span class="fu">as</span>(tm_sp, <span class="st">"owin"</span>)</span>
<span id="cb80-3"><a href="#cb80-3" aria-hidden="true" tabindex="-1"></a>ck_owin <span class="ot">=</span> <span class="fu">as</span>(ck_sp, <span class="st">"owin"</span>)</span>
<span id="cb80-4"><a href="#cb80-4" aria-hidden="true" tabindex="-1"></a>jw_owin <span class="ot">=</span> <span class="fu">as</span>(jw_sp, <span class="st">"owin"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="combining-grab-trips-points-and-the-study-area" class="level4">
<h4 class="anchored" data-anchor-id="combining-grab-trips-points-and-the-study-area"><strong>COMBINING Grab Trips POINTS AND THE STUDY AREA</strong></h4>
<p>By using the code chunk below, we are able to extract grab trips destinations that is within the specific region to do our analysis later on.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb81"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb81-1"><a href="#cb81-1" aria-hidden="true" tabindex="-1"></a>grab_trips_pg_ppp <span class="ot">=</span> grab_trips_ppp[pg_owin]</span>
<span id="cb81-2"><a href="#cb81-2" aria-hidden="true" tabindex="-1"></a>grab_trips_tm_ppp <span class="ot">=</span> grab_trips_ppp[tm_owin]</span>
<span id="cb81-3"><a href="#cb81-3" aria-hidden="true" tabindex="-1"></a>grab_trips_ck_ppp <span class="ot">=</span> grab_trips_ppp[ck_owin]</span>
<span id="cb81-4"><a href="#cb81-4" aria-hidden="true" tabindex="-1"></a>grab_trips_jw_ppp <span class="ot">=</span> grab_trips_ppp[jw_owin]</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Next, <em>rescale()</em> function is used to trasnform the unit of measurement from metre to kilometre.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb82"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb82-1"><a href="#cb82-1" aria-hidden="true" tabindex="-1"></a>grab_trips_pg_ppp.km <span class="ot">=</span> <span class="fu">rescale</span>(grab_trips_pg_ppp, <span class="dv">1000</span>, <span class="st">"km"</span>)</span>
<span id="cb82-2"><a href="#cb82-2" aria-hidden="true" tabindex="-1"></a>grab_trips_tm_ppp.km <span class="ot">=</span> <span class="fu">rescale</span>(grab_trips_tm_ppp, <span class="dv">1000</span>, <span class="st">"km"</span>)</span>
<span id="cb82-3"><a href="#cb82-3" aria-hidden="true" tabindex="-1"></a>grab_trips_ck_ppp.km <span class="ot">=</span> <span class="fu">rescale</span>(grab_trips_ck_ppp, <span class="dv">1000</span>, <span class="st">"km"</span>)</span>
<span id="cb82-4"><a href="#cb82-4" aria-hidden="true" tabindex="-1"></a>grab_tripse_jw_ppp.km <span class="ot">=</span> <span class="fu">rescale</span>(grab_trips_jw_ppp, <span class="dv">1000</span>, <span class="st">"km"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Let’s plot these four study areas and the locations of the grab trip destinations.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb83"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb83-1"><a href="#cb83-1" aria-hidden="true" tabindex="-1"></a><span class="fu">par</span>(<span class="at">mfrow=</span><span class="fu">c</span>(<span class="dv">2</span>,<span class="dv">2</span>))</span>
<span id="cb83-2"><a href="#cb83-2" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(grab_trips_pg_ppp.km, <span class="at">main=</span><span class="st">"Changi"</span>)</span>
<span id="cb83-3"><a href="#cb83-3" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(grab_trips_tm_ppp.km, <span class="at">main=</span><span class="st">"Marine Parade"</span>)</span>
<span id="cb83-4"><a href="#cb83-4" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(grab_trips_ck_ppp.km, <span class="at">main=</span><span class="st">"Choa Chu Kang"</span>)</span>
<span id="cb83-5"><a href="#cb83-5" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(grab_tripse_jw_ppp.km, <span class="at">main=</span><span class="st">"Jurong West"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Take-home_Ex01_3_files/figure-html/unnamed-chunk-56-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>As we can see, the lower bottom part of Pungol is heavily saturated with driving trip destination end points.</p>
</section>
<section id="computing-kde" class="level4">
<h4 class="anchored" data-anchor-id="computing-kde"><strong>COMPUTING KDE</strong></h4>
<p>The code chunk below will be used to compute the KDE of these four planning area. <strong><em>bw.diggle</em></strong> method is used to derive the bandwidth of each</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb84"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb84-1"><a href="#cb84-1" aria-hidden="true" tabindex="-1"></a><span class="fu">par</span>(<span class="at">mfrow=</span><span class="fu">c</span>(<span class="dv">2</span>,<span class="dv">2</span>))</span>
<span id="cb84-2"><a href="#cb84-2" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(<span class="fu">density</span>(grab_trips_pg_ppp.km, </span>
<span id="cb84-3"><a href="#cb84-3" aria-hidden="true" tabindex="-1"></a>             <span class="at">sigma=</span>bw.diggle, </span>
<span id="cb84-4"><a href="#cb84-4" aria-hidden="true" tabindex="-1"></a>             <span class="at">edge=</span><span class="cn">TRUE</span>, </span>
<span id="cb84-5"><a href="#cb84-5" aria-hidden="true" tabindex="-1"></a>             <span class="at">kernel=</span><span class="st">"gaussian"</span>),</span>
<span id="cb84-6"><a href="#cb84-6" aria-hidden="true" tabindex="-1"></a>     <span class="at">main=</span><span class="st">"Changi"</span>)</span>
<span id="cb84-7"><a href="#cb84-7" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(<span class="fu">density</span>(grab_trips_tm_ppp.km, </span>
<span id="cb84-8"><a href="#cb84-8" aria-hidden="true" tabindex="-1"></a>             <span class="at">sigma=</span>bw.diggle, </span>
<span id="cb84-9"><a href="#cb84-9" aria-hidden="true" tabindex="-1"></a>             <span class="at">edge=</span><span class="cn">TRUE</span>, </span>
<span id="cb84-10"><a href="#cb84-10" aria-hidden="true" tabindex="-1"></a>             <span class="at">kernel=</span><span class="st">"gaussian"</span>),</span>
<span id="cb84-11"><a href="#cb84-11" aria-hidden="true" tabindex="-1"></a>     <span class="at">main=</span><span class="st">"Marine Parade"</span>)</span>
<span id="cb84-12"><a href="#cb84-12" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(<span class="fu">density</span>(grab_trips_ck_ppp.km, </span>
<span id="cb84-13"><a href="#cb84-13" aria-hidden="true" tabindex="-1"></a>             <span class="at">sigma=</span>bw.diggle, </span>
<span id="cb84-14"><a href="#cb84-14" aria-hidden="true" tabindex="-1"></a>             <span class="at">edge=</span><span class="cn">TRUE</span>, </span>
<span id="cb84-15"><a href="#cb84-15" aria-hidden="true" tabindex="-1"></a>             <span class="at">kernel=</span><span class="st">"gaussian"</span>),</span>
<span id="cb84-16"><a href="#cb84-16" aria-hidden="true" tabindex="-1"></a>     <span class="at">main=</span><span class="st">"Choa Chu Kang"</span>)</span>
<span id="cb84-17"><a href="#cb84-17" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(<span class="fu">density</span>(grab_tripse_jw_ppp.km, </span>
<span id="cb84-18"><a href="#cb84-18" aria-hidden="true" tabindex="-1"></a>             <span class="at">sigma=</span>bw.diggle, </span>
<span id="cb84-19"><a href="#cb84-19" aria-hidden="true" tabindex="-1"></a>             <span class="at">edge=</span><span class="cn">TRUE</span>, </span>
<span id="cb84-20"><a href="#cb84-20" aria-hidden="true" tabindex="-1"></a>             <span class="at">kernel=</span><span class="st">"gaussian"</span>),</span>
<span id="cb84-21"><a href="#cb84-21" aria-hidden="true" tabindex="-1"></a>     <span class="at">main=</span><span class="st">"JUrong West"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Take-home_Ex01_3_files/figure-html/unnamed-chunk-57-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
</section>
</section>
</section>
<section id="nearest-neighbour-analysis" class="level2">
<h2 class="anchored" data-anchor-id="nearest-neighbour-analysis"><strong>NEAREST NEIGHBOUR ANALYSIS</strong></h2>
<p>In this section, we will perform the Clark-Evans test of aggregation for a spatial point pattern by using <a href="https://www.rdocumentation.org/packages/spatstat/versions/1.63-3/topics/clarkevans.test"><em>clarkevans.test()</em></a> of <strong>statspat</strong>.</p>
<p>The test hypotheses are:</p>
<p>Ho = The distribution of grab trips destinations are randomly distributed.</p>
<p>H1= The distribution of grab trips destinations are not randomly distributed.</p>
<p>The 95% confident interval will be used.</p>
<section id="testing-spatial-point-patterns-using-clark-and-evans-test" class="level3">
<h3 class="anchored" data-anchor-id="testing-spatial-point-patterns-using-clark-and-evans-test"><strong>TESTING SPATIAL POINT PATTERNS USING CLARK AND EVANS TEST</strong></h3>
</section>
<section id="section" class="level3">
<h3 class="anchored" data-anchor-id="section"></h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb85"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb85-1"><a href="#cb85-1" aria-hidden="true" tabindex="-1"></a><span class="fu">clarkevans.test</span>(grab_trips_ppp_SG,</span>
<span id="cb85-2"><a href="#cb85-2" aria-hidden="true" tabindex="-1"></a>                <span class="at">correction=</span><span class="st">"none"</span>,</span>
<span id="cb85-3"><a href="#cb85-3" aria-hidden="true" tabindex="-1"></a>                <span class="at">clipregion=</span><span class="st">"sg_owin"</span>,</span>
<span id="cb85-4"><a href="#cb85-4" aria-hidden="true" tabindex="-1"></a>                <span class="at">alternative=</span><span class="fu">c</span>(<span class="st">"clustered"</span>),</span>
<span id="cb85-5"><a href="#cb85-5" aria-hidden="true" tabindex="-1"></a>                <span class="at">nsim=</span><span class="dv">99</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Clark-Evans test
    No edge correction
    Z-test

data:  grab_trips_ppp_SG
R = 0.28436, p-value &lt; 2.2e-16
alternative hypothesis: clustered (R &lt; 1)</code></pre>
</div>
</div>
</section>
<section id="clark-and-evans-test-choa-chu-kang-planning-area" class="level3">
<h3 class="anchored" data-anchor-id="clark-and-evans-test-choa-chu-kang-planning-area"><strong>CLARK AND EVANS TEST: CHOA CHU KANG PLANNING AREA</strong></h3>
<p>In the code chunk below, <a href="https://rdrr.io/cran/spatstat/man/clarkevans.test.html"><em>clarkevans.test()</em></a> of <strong>spatstat</strong> is used to performs Clark-Evans test of aggregation for grab trip destinations in Choa Chu Kang planning area.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb87"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb87-1"><a href="#cb87-1" aria-hidden="true" tabindex="-1"></a><span class="fu">clarkevans.test</span>(grab_trips_ck_ppp,</span>
<span id="cb87-2"><a href="#cb87-2" aria-hidden="true" tabindex="-1"></a>                <span class="at">correction=</span><span class="st">"none"</span>,</span>
<span id="cb87-3"><a href="#cb87-3" aria-hidden="true" tabindex="-1"></a>                <span class="at">clipregion=</span><span class="cn">NULL</span>,</span>
<span id="cb87-4"><a href="#cb87-4" aria-hidden="true" tabindex="-1"></a>                <span class="at">alternative=</span><span class="fu">c</span>(<span class="st">"two.sided"</span>),</span>
<span id="cb87-5"><a href="#cb87-5" aria-hidden="true" tabindex="-1"></a>                <span class="at">nsim=</span><span class="dv">999</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Clark-Evans test
    No edge correction
    Z-test

data:  grab_trips_ck_ppp
R = 0.4768, p-value &lt; 2.2e-16
alternative hypothesis: two-sided</code></pre>
</div>
</div>
<p>Since R &lt; 1, it indicates there is a clustering of destinations at this Chua Chu Kang area.</p>
</section>
<section id="clark-and-evans-test-changi-planning-area" class="level3">
<h3 class="anchored" data-anchor-id="clark-and-evans-test-changi-planning-area"><strong>CLARK AND EVANS TEST: CHANGI PLANNING AREA</strong></h3>
<p>In the code chunk below, the similar test is used to analyse the spatial point patterns of grab trips destinations in Changi planning area.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb89"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb89-1"><a href="#cb89-1" aria-hidden="true" tabindex="-1"></a><span class="fu">clarkevans.test</span>(grab_trips_pg_ppp,</span>
<span id="cb89-2"><a href="#cb89-2" aria-hidden="true" tabindex="-1"></a>                <span class="at">correction=</span><span class="st">"none"</span>,</span>
<span id="cb89-3"><a href="#cb89-3" aria-hidden="true" tabindex="-1"></a>                <span class="at">clipregion=</span><span class="cn">NULL</span>,</span>
<span id="cb89-4"><a href="#cb89-4" aria-hidden="true" tabindex="-1"></a>                <span class="at">alternative=</span><span class="fu">c</span>(<span class="st">"two.sided"</span>),</span>
<span id="cb89-5"><a href="#cb89-5" aria-hidden="true" tabindex="-1"></a>                <span class="at">nsim=</span><span class="dv">999</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Clark-Evans test
    No edge correction
    Z-test

data:  grab_trips_pg_ppp
R = 0.11628, p-value &lt; 2.2e-16
alternative hypothesis: two-sided</code></pre>
</div>
</div>
<p>Since R &lt; 1, it indicates there is a clustering of destinations at this Changi area. There is more clustering of points than Chua Chu Kang area since the R values of Changi area is less than that of Chua Chu Kang area.</p>
</section>
</section>
<section id="network-constraint-layers" class="level2">
<h2 class="anchored" data-anchor-id="network-constraint-layers">Network constraint layers</h2>
<p>What are the different layers available as part of the gis dataset? There is road networks, street networks and many more. Lets add only the road layer with the name ‘gis_osm_roads_free_1’:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb91"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb91-1"><a href="#cb91-1" aria-hidden="true" tabindex="-1"></a>road_network <span class="ot">&lt;-</span> <span class="fu">st_read</span>(<span class="at">dsn =</span> <span class="st">"../../data/takehomeassigment1/malaysia-singapore-brunei-latest-free/"</span>, <span class="at">layer =</span> <span class="st">"gis_osm_roads_free_1"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Reading layer `gis_osm_roads_free_1' from data source 
  `/Users/maarunipandithurai/Documents/maars202/geospatial/IS415-GAA/data/takehomeassigment1/malaysia-singapore-brunei-latest-free' 
  using driver `ESRI Shapefile'
Simple feature collection with 1766969 features and 10 fields
Geometry type: LINESTRING
Dimension:     XY
Bounding box:  xmin: 99.66041 ymin: 0.8021131 xmax: 119.2601 ymax: 7.514393
Geodetic CRS:  WGS 84</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb93"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb93-1"><a href="#cb93-1" aria-hidden="true" tabindex="-1"></a><span class="co"># typeof(road_network)  #&lt;-- list type</span></span>
<span id="cb93-2"><a href="#cb93-2" aria-hidden="true" tabindex="-1"></a>road_network</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Simple feature collection with 1766969 features and 10 fields
Geometry type: LINESTRING
Dimension:     XY
Bounding box:  xmin: 99.66041 ymin: 0.8021131 xmax: 119.2601 ymax: 7.514393
Geodetic CRS:  WGS 84
First 10 features:
    osm_id code      fclass                   name  ref oneway maxspeed layer
1  4386520 5113     primary           Orchard Road &lt;NA&gt;      F       50     0
2  4578273 5114   secondary    Jalan Bukit Bintang &lt;NA&gt;      F        0     0
3  4579495 5122 residential         Jalan Nagasari &lt;NA&gt;      B        0     0
4  4579533 5122 residential  Persiaran Raja Chulan &lt;NA&gt;      B        0     0
5  4579534 5122 residential           Jalan Ceylon &lt;NA&gt;      B        0     0
6  4579536 5122 residential Changkat Bukit Bintang &lt;NA&gt;      F        0     0
7  4584656 5141     service                   &lt;NA&gt; &lt;NA&gt;      F        0    -1
8  4585475 5122 residential       Jalan Hang Lekir &lt;NA&gt;      F        0     0
9  4585480 5122 residential           Jalan Beremi &lt;NA&gt;      F        0     0
10 4585482 5122 residential         Jalan Berangan &lt;NA&gt;      F        0     0
   bridge tunnel                       geometry
1       F      F LINESTRING (103.8301 1.3060...
2       F      F LINESTRING (101.7226 3.1478...
3       F      F LINESTRING (101.7084 3.1473...
4       F      F LINESTRING (101.7043 3.1468...
5       F      F LINESTRING (101.7033 3.1476...
6       F      F LINESTRING (101.7088 3.1470...
7       F      T LINESTRING (101.6995 3.1470...
8       F      F LINESTRING (101.6959 3.1443...
9       F      F LINESTRING (101.71 3.1473, ...
10      F      F LINESTRING (101.7103 3.1472...</code></pre>
</div>
</div>
<p>The Projected CRS for the road_network above is SVY21 / Singapore TM due to the st_transform method we applied earlier when importing the data.</p>
<p>Let us analyse a linestring’s bounding box:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb95"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb95-1"><a href="#cb95-1" aria-hidden="true" tabindex="-1"></a>i <span class="ot">&lt;-</span> <span class="dv">900</span></span>
<span id="cb95-2"><a href="#cb95-2" aria-hidden="true" tabindex="-1"></a>inside <span class="ot">&lt;-</span> <span class="fu">inside.owin</span>(<span class="fu">attributes</span>(road_network<span class="sc">$</span>geometry[i])<span class="sc">$</span>bbox<span class="sc">$</span>xmin, (road_network<span class="sc">$</span>geometry[i])<span class="sc">$</span>bbox<span class="sc">$</span>ymin, sg_owin)</span>
<span id="cb95-3"><a href="#cb95-3" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">"xmin of bounding box for linestring in row "</span>, i, <span class="st">":"</span>, <span class="fu">attributes</span>(road_network<span class="sc">$</span>geometry[i])<span class="sc">$</span>bbox<span class="sc">$</span>xmin, <span class="st">"</span><span class="sc">\n</span><span class="st">"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>xmin of bounding box for linestring in row  900 : 102.8441 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb97"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb97-1"><a href="#cb97-1" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">"xmax of bounding box for linestring in row "</span>, i, <span class="st">":"</span>, <span class="fu">attributes</span>(road_network<span class="sc">$</span>geometry[i])<span class="sc">$</span>bbox<span class="sc">$</span>xmax, <span class="st">"</span><span class="sc">\n</span><span class="st">"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>xmax of bounding box for linestring in row  900 : 102.8445 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb99"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb99-1"><a href="#cb99-1" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">"ymin of bounding box for linestring in row "</span>, i, <span class="st">":"</span>, <span class="fu">attributes</span>(road_network<span class="sc">$</span>geometry[i])<span class="sc">$</span>bbox<span class="sc">$</span>ymin, <span class="st">"</span><span class="sc">\n</span><span class="st">"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>ymin of bounding box for linestring in row  900 : 2.490684 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb101"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb101-1"><a href="#cb101-1" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">"xmin of bounding box for linestring in row "</span>, i, <span class="st">":"</span>, <span class="fu">attributes</span>(road_network<span class="sc">$</span>geometry[i])<span class="sc">$</span>bbox<span class="sc">$</span>ymax, <span class="st">"</span><span class="sc">\n</span><span class="st">"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>xmin of bounding box for linestring in row  900 : 2.491354 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb103"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb103-1"><a href="#cb103-1" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">"Does it fall inside owin object of sg:"</span>, <span class="fu">ifelse</span>(inside, <span class="st">"yes"</span>, <span class="st">"no"</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Does it fall inside owin object of sg: </code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb105"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb105-1"><a href="#cb105-1" aria-hidden="true" tabindex="-1"></a>i <span class="ot">&lt;-</span> <span class="dv">1</span></span>
<span id="cb105-2"><a href="#cb105-2" aria-hidden="true" tabindex="-1"></a><span class="fu">inside.owin</span>(<span class="fu">attributes</span>(road_network<span class="sc">$</span>geometry[i])<span class="sc">$</span>bbox<span class="sc">$</span>xmin, (road_network<span class="sc">$</span>geometry[i])<span class="sc">$</span>bbox<span class="sc">$</span>ymin, sg_owin)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>logical(0)</code></pre>
</div>
</div>
<p>Since Singapore falls inside the bounding box of xmin = 103.54, xmax = 104.100274, ymin = 1.159704 and ymax = 1.515345, we will filter our rows to make the dataset of road networks smaller and more manageable. We are using txtProgressBar object to keep track of our progress for assigning rows as within Singapore or not since this process will take around 5 minutes.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb107"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb107-1"><a href="#cb107-1" aria-hidden="true" tabindex="-1"></a>pct_circ <span class="ot">&lt;-</span> <span class="fu">list</span>()  <span class="do">## create an empty list to store values</span></span>
<span id="cb107-2"><a href="#cb107-2" aria-hidden="true" tabindex="-1"></a>n_iter <span class="ot">=</span> <span class="fu">nrow</span>(road_network)</span>
<span id="cb107-3"><a href="#cb107-3" aria-hidden="true" tabindex="-1"></a><span class="co"># Initializes the progress bar</span></span>
<span id="cb107-4"><a href="#cb107-4" aria-hidden="true" tabindex="-1"></a>pb <span class="ot">&lt;-</span> <span class="fu">txtProgressBar</span>(<span class="at">min =</span> <span class="dv">0</span>,      <span class="co"># Minimum value of the progress bar</span></span>
<span id="cb107-5"><a href="#cb107-5" aria-hidden="true" tabindex="-1"></a>                     <span class="at">max =</span> n_iter, <span class="co"># Maximum value of the progress bar</span></span>
<span id="cb107-6"><a href="#cb107-6" aria-hidden="true" tabindex="-1"></a>                     <span class="at">style =</span> <span class="dv">3</span>,    <span class="co"># Progress bar style (also available style = 1 and style = 2)</span></span>
<span id="cb107-7"><a href="#cb107-7" aria-hidden="true" tabindex="-1"></a>                     <span class="at">width =</span> <span class="dv">50</span>,   <span class="co"># Progress bar width. Defaults to getOption("width")</span></span>
<span id="cb107-8"><a href="#cb107-8" aria-hidden="true" tabindex="-1"></a>                     <span class="at">char =</span> <span class="st">"="</span>)   <span class="co"># Character used to create the bar</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
  |                                                        
  |                                                  |   0%</code></pre>
</div>
<div class="sourceCode cell-code" id="cb109"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb109-1"><a href="#cb109-1" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span>(i <span class="cf">in</span> <span class="dv">1</span><span class="sc">:</span><span class="fu">nrow</span>(road_network)) { <span class="co"># loop over each row</span></span>
<span id="cb109-2"><a href="#cb109-2" aria-hidden="true" tabindex="-1"></a>  pct_circ[i] <span class="ot">&lt;-</span> <span class="fu">attributes</span>(road_network<span class="sc">$</span>geometry[i])<span class="sc">$</span>bbox<span class="sc">$</span>xmin <span class="sc">&gt;</span> <span class="fl">103.54</span>     <span class="sc">&amp;</span> <span class="fu">attributes</span>(road_network<span class="sc">$</span>geometry[i])<span class="sc">$</span>bbox<span class="sc">$</span>xmax <span class="sc">&lt;</span> <span class="fl">104.100274</span> <span class="sc">&amp;</span> <span class="fu">attributes</span>(road_network<span class="sc">$</span>geometry[i])<span class="sc">$</span>bbox<span class="sc">$</span>ymin <span class="sc">&gt;</span> <span class="fl">1.159704</span> <span class="sc">&amp;</span> <span class="fu">attributes</span>(road_network<span class="sc">$</span>geometry[i])<span class="sc">$</span>bbox<span class="sc">$</span>ymax <span class="sc">&lt;</span> <span class="fl">1.515345</span></span>
<span id="cb109-3"><a href="#cb109-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">setTxtProgressBar</span>(pb,i)</span>
<span id="cb109-4"><a href="#cb109-4" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb109-5"><a href="#cb109-5" aria-hidden="true" tabindex="-1"></a>} <span class="co"># End for loop</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
  |                                                        
  |                                                  |   1%
  |                                                        
  |=                                                 |   1%
  |                                                        
  |=                                                 |   2%
  |                                                        
  |=                                                 |   3%
  |                                                        
  |==                                                |   3%
  |                                                        
  |==                                                |   4%
  |                                                        
  |==                                                |   5%
  |                                                        
  |===                                               |   5%
  |                                                        
  |===                                               |   6%
  |                                                        
  |===                                               |   7%
  |                                                        
  |====                                              |   7%
  |                                                        
  |====                                              |   8%
  |                                                        
  |====                                              |   9%
  |                                                        
  |=====                                             |   9%
  |                                                        
  |=====                                             |  10%
  |                                                        
  |=====                                             |  11%
  |                                                        
  |======                                            |  11%
  |                                                        
  |======                                            |  12%
  |                                                        
  |======                                            |  13%
  |                                                        
  |=======                                           |  13%
  |                                                        
  |=======                                           |  14%
  |                                                        
  |=======                                           |  15%
  |                                                        
  |========                                          |  15%
  |                                                        
  |========                                          |  16%
  |                                                        
  |========                                          |  17%
  |                                                        
  |=========                                         |  17%
  |                                                        
  |=========                                         |  18%
  |                                                        
  |=========                                         |  19%
  |                                                        
  |==========                                        |  19%
  |                                                        
  |==========                                        |  20%
  |                                                        
  |==========                                        |  21%
  |                                                        
  |===========                                       |  21%
  |                                                        
  |===========                                       |  22%
  |                                                        
  |===========                                       |  23%
  |                                                        
  |============                                      |  23%
  |                                                        
  |============                                      |  24%
  |                                                        
  |============                                      |  25%
  |                                                        
  |=============                                     |  25%
  |                                                        
  |=============                                     |  26%
  |                                                        
  |=============                                     |  27%
  |                                                        
  |==============                                    |  27%
  |                                                        
  |==============                                    |  28%
  |                                                        
  |==============                                    |  29%
  |                                                        
  |===============                                   |  29%
  |                                                        
  |===============                                   |  30%
  |                                                        
  |===============                                   |  31%
  |                                                        
  |================                                  |  31%
  |                                                        
  |================                                  |  32%
  |                                                        
  |================                                  |  33%
  |                                                        
  |=================                                 |  33%
  |                                                        
  |=================                                 |  34%
  |                                                        
  |=================                                 |  35%
  |                                                        
  |==================                                |  35%
  |                                                        
  |==================                                |  36%
  |                                                        
  |==================                                |  37%
  |                                                        
  |===================                               |  37%
  |                                                        
  |===================                               |  38%
  |                                                        
  |===================                               |  39%
  |                                                        
  |====================                              |  39%
  |                                                        
  |====================                              |  40%
  |                                                        
  |====================                              |  41%
  |                                                        
  |=====================                             |  41%
  |                                                        
  |=====================                             |  42%
  |                                                        
  |=====================                             |  43%
  |                                                        
  |======================                            |  43%
  |                                                        
  |======================                            |  44%
  |                                                        
  |======================                            |  45%
  |                                                        
  |=======================                           |  45%
  |                                                        
  |=======================                           |  46%
  |                                                        
  |=======================                           |  47%
  |                                                        
  |========================                          |  47%
  |                                                        
  |========================                          |  48%
  |                                                        
  |========================                          |  49%
  |                                                        
  |=========================                         |  49%
  |                                                        
  |=========================                         |  50%
  |                                                        
  |=========================                         |  51%
  |                                                        
  |==========================                        |  51%
  |                                                        
  |==========================                        |  52%
  |                                                        
  |==========================                        |  53%
  |                                                        
  |===========================                       |  53%
  |                                                        
  |===========================                       |  54%
  |                                                        
  |===========================                       |  55%
  |                                                        
  |============================                      |  55%
  |                                                        
  |============================                      |  56%
  |                                                        
  |============================                      |  57%
  |                                                        
  |=============================                     |  57%
  |                                                        
  |=============================                     |  58%
  |                                                        
  |=============================                     |  59%
  |                                                        
  |==============================                    |  59%
  |                                                        
  |==============================                    |  60%
  |                                                        
  |==============================                    |  61%
  |                                                        
  |===============================                   |  61%
  |                                                        
  |===============================                   |  62%
  |                                                        
  |===============================                   |  63%
  |                                                        
  |================================                  |  63%
  |                                                        
  |================================                  |  64%
  |                                                        
  |================================                  |  65%
  |                                                        
  |=================================                 |  65%
  |                                                        
  |=================================                 |  66%
  |                                                        
  |=================================                 |  67%
  |                                                        
  |==================================                |  67%
  |                                                        
  |==================================                |  68%
  |                                                        
  |==================================                |  69%
  |                                                        
  |===================================               |  69%
  |                                                        
  |===================================               |  70%
  |                                                        
  |===================================               |  71%
  |                                                        
  |====================================              |  71%
  |                                                        
  |====================================              |  72%
  |                                                        
  |====================================              |  73%
  |                                                        
  |=====================================             |  73%
  |                                                        
  |=====================================             |  74%
  |                                                        
  |=====================================             |  75%
  |                                                        
  |======================================            |  75%
  |                                                        
  |======================================            |  76%
  |                                                        
  |======================================            |  77%
  |                                                        
  |=======================================           |  77%
  |                                                        
  |=======================================           |  78%
  |                                                        
  |=======================================           |  79%
  |                                                        
  |========================================          |  79%
  |                                                        
  |========================================          |  80%
  |                                                        
  |========================================          |  81%
  |                                                        
  |=========================================         |  81%
  |                                                        
  |=========================================         |  82%
  |                                                        
  |=========================================         |  83%
  |                                                        
  |==========================================        |  83%
  |                                                        
  |==========================================        |  84%
  |                                                        
  |==========================================        |  85%
  |                                                        
  |===========================================       |  85%
  |                                                        
  |===========================================       |  86%
  |                                                        
  |===========================================       |  87%
  |                                                        
  |============================================      |  87%
  |                                                        
  |============================================      |  88%
  |                                                        
  |============================================      |  89%
  |                                                        
  |=============================================     |  89%
  |                                                        
  |=============================================     |  90%
  |                                                        
  |=============================================     |  91%
  |                                                        
  |==============================================    |  91%
  |                                                        
  |==============================================    |  92%
  |                                                        
  |==============================================    |  93%
  |                                                        
  |===============================================   |  93%
  |                                                        
  |===============================================   |  94%
  |                                                        
  |===============================================   |  95%
  |                                                        
  |================================================  |  95%
  |                                                        
  |================================================  |  96%
  |                                                        
  |================================================  |  97%
  |                                                        
  |================================================= |  97%
  |                                                        
  |================================================= |  98%
  |                                                        
  |================================================= |  99%
  |                                                        
  |==================================================|  99%
  |                                                        
  |==================================================| 100%</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb111"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb111-1"><a href="#cb111-1" aria-hidden="true" tabindex="-1"></a><span class="co">#rbind(Orange,m)</span></span>
<span id="cb111-2"><a href="#cb111-2" aria-hidden="true" tabindex="-1"></a>m <span class="ot">&lt;-</span> <span class="fu">matrix</span>(<span class="fu">unlist</span>(pct_circ), <span class="at">nrow =</span> <span class="fu">length</span>(pct_circ))</span>
<span id="cb111-3"><a href="#cb111-3" aria-hidden="true" tabindex="-1"></a>df3 <span class="ot">&lt;-</span> <span class="fu">cbind</span>(road_network, m) </span>
<span id="cb111-4"><a href="#cb111-4" aria-hidden="true" tabindex="-1"></a>df3</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Simple feature collection with 1766969 features and 11 fields
Geometry type: LINESTRING
Dimension:     XY
Bounding box:  xmin: 99.66041 ymin: 0.8021131 xmax: 119.2601 ymax: 7.514393
Geodetic CRS:  WGS 84
First 10 features:
    osm_id code      fclass                   name  ref oneway maxspeed layer
1  4386520 5113     primary           Orchard Road &lt;NA&gt;      F       50     0
2  4578273 5114   secondary    Jalan Bukit Bintang &lt;NA&gt;      F        0     0
3  4579495 5122 residential         Jalan Nagasari &lt;NA&gt;      B        0     0
4  4579533 5122 residential  Persiaran Raja Chulan &lt;NA&gt;      B        0     0
5  4579534 5122 residential           Jalan Ceylon &lt;NA&gt;      B        0     0
6  4579536 5122 residential Changkat Bukit Bintang &lt;NA&gt;      F        0     0
7  4584656 5141     service                   &lt;NA&gt; &lt;NA&gt;      F        0    -1
8  4585475 5122 residential       Jalan Hang Lekir &lt;NA&gt;      F        0     0
9  4585480 5122 residential           Jalan Beremi &lt;NA&gt;      F        0     0
10 4585482 5122 residential         Jalan Berangan &lt;NA&gt;      F        0     0
   bridge tunnel     m                       geometry
1       F      F  TRUE LINESTRING (103.8301 1.3060...
2       F      F FALSE LINESTRING (101.7226 3.1478...
3       F      F FALSE LINESTRING (101.7084 3.1473...
4       F      F FALSE LINESTRING (101.7043 3.1468...
5       F      F FALSE LINESTRING (101.7033 3.1476...
6       F      F FALSE LINESTRING (101.7088 3.1470...
7       F      T FALSE LINESTRING (101.6995 3.1470...
8       F      F FALSE LINESTRING (101.6959 3.1443...
9       F      F FALSE LINESTRING (101.71 3.1473, ...
10      F      F FALSE LINESTRING (101.7103 3.1472...</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb113"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb113-1"><a href="#cb113-1" aria-hidden="true" tabindex="-1"></a>filtered_road_networks <span class="ot">&lt;-</span> <span class="fu">filter</span>(df3, m <span class="sc">==</span> <span class="cn">TRUE</span>)</span>
<span id="cb113-2"><a href="#cb113-2" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>( <span class="st">"Percentage of dataset we are dealing with now"</span>, (<span class="fu">dim</span>(filtered_road_networks)[<span class="dv">1</span>] <span class="sc">/</span> <span class="fu">dim</span>(road_network)[<span class="dv">1</span>]) <span class="sc">*</span> <span class="dv">100</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Percentage of dataset we are dealing with now 15.67917</code></pre>
</div>
</div>
<p>We are only dealing with 15.7% of the original road network dataset that lies in and near Singapore.</p>
<p>We need to project this geospatial lines data to Singapore’s coordinate system with crs = 3414.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb115"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb115-1"><a href="#cb115-1" aria-hidden="true" tabindex="-1"></a>filtered_road_networks <span class="ot">&lt;-</span> <span class="fu">st_transform</span>(filtered_road_networks, <span class="at">crs =</span> <span class="dv">3414</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb116"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb116-1"><a href="#cb116-1" aria-hidden="true" tabindex="-1"></a>road_network_sp_lines <span class="ot">&lt;-</span> <span class="fu">as_Spatial</span>(filtered_road_networks<span class="sc">$</span>geometry)</span>
<span id="cb116-2"><a href="#cb116-2" aria-hidden="true" tabindex="-1"></a>road_network_sp_lines</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>class       : SpatialLines 
features    : 277046 
extent      : -4633.586, 57669.67, 15901.59, 55185.13  (xmin, xmax, ymin, ymax)
crs         : +proj=tmerc +lat_0=1.36666666666667 +lon_0=103.833333333333 +k=1 +x_0=28001.642 +y_0=38744.572 +ellps=WGS84 +towgs84=0,0,0,0,0,0,0 +units=m +no_defs </code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb118"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb118-1"><a href="#cb118-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(road_network_sp_lines)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Take-home_Ex01_3_files/figure-html/unnamed-chunk-70-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb119"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb119-1"><a href="#cb119-1" aria-hidden="true" tabindex="-1"></a>lixels <span class="ot">&lt;-</span> <span class="fu">lixelize_lines.mc</span>(filtered_road_networks, </span>
<span id="cb119-2"><a href="#cb119-2" aria-hidden="true" tabindex="-1"></a>                         <span class="dv">700</span>, </span>
<span id="cb119-3"><a href="#cb119-3" aria-hidden="true" tabindex="-1"></a>                         <span class="at">mindist =</span> <span class="dv">350</span>)</span>
<span id="cb119-4"><a href="#cb119-4" aria-hidden="true" tabindex="-1"></a>lixels</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Simple feature collection with 278508 features and 12 fields
Geometry type: LINESTRING
Dimension:     XY
Bounding box:  xmin: -4633.586 ymin: 15901.59 xmax: 57669.67 ymax: 55185.13
Projected CRS: SVY21 / Singapore TM
First 10 features:
   lineID  osm_id code      fclass              name  ref oneway maxspeed layer
1       1 4386520 5113     primary      Orchard Road &lt;NA&gt;      F       50     0
2       2 4887867 5122 residential  Hougang Avenue 1 &lt;NA&gt;      B       50     0
3       3 8096835 5113     primary       Scotts Road &lt;NA&gt;      F       60     0
4       4 9584642 5115    tertiary     Keng Lee Road &lt;NA&gt;      F       50     0
5       5 9584847 5153     footway              &lt;NA&gt; &lt;NA&gt;      B        0     0
6       6 9585045 5113     primary       Newton Road &lt;NA&gt;      F       60     0
7       7 9585074 5122 residential      Sarkies Road &lt;NA&gt;      B       50     0
8       8 9585621 5113     primary     Paterson Road &lt;NA&gt;      F       50     0
9       9 9585771 5113     primary Orchard Boulevard &lt;NA&gt;      F       50     0
10     10 9586040 5113     primary     Paterson Road &lt;NA&gt;      F       50     0
   bridge tunnel    m                       geometry
1       F      F TRUE LINESTRING (27637.52 32038....
2       F      F TRUE LINESTRING (34016.12 36785....
3       F      F TRUE LINESTRING (28588.71 32765....
4       F      F TRUE LINESTRING (29165.25 32888....
5       F      F TRUE LINESTRING (28834.55 32990....
6       F      F TRUE LINESTRING (28664.35 32858....
7       F      F TRUE LINESTRING (28433.13 32988....
8       F      F TRUE LINESTRING (27835.44 31930....
9       F      F TRUE LINESTRING (28168.89 31418....
10      F      F TRUE LINESTRING (27685.73 31733....</code></pre>
</div>
</div>
<p>Using multicore support for this function as there are alot of roads that need to be cut into specified minimal distance.</p>
<section id="generating-line-centre-points" class="level3">
<h3 class="anchored" data-anchor-id="generating-line-centre-points"><strong>7.6.2 GENERATING LINE CENTRE POINTS</strong></h3>
<p>Next, <em>lines_center()</em> of <strong>spNetwork</strong> will be used to generate a SpatialPointsDataFrame (i.e.&nbsp;samples) with line centre points as shown in the code chunk below.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb121"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb121-1"><a href="#cb121-1" aria-hidden="true" tabindex="-1"></a>samples <span class="ot">&lt;-</span> <span class="fu">lines_center</span>(lixels)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>The points are located at center of the line based on the length of the line.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb122"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb122-1"><a href="#cb122-1" aria-hidden="true" tabindex="-1"></a>trip_endings_df <span class="ot">&lt;-</span> <span class="fu">st_as_sf</span>(destination_df, </span>
<span id="cb122-2"><a href="#cb122-2" aria-hidden="true" tabindex="-1"></a>                       <span class="at">coords =</span> <span class="fu">c</span>(<span class="st">"rawlng"</span>, <span class="st">"rawlat"</span>),</span>
<span id="cb122-3"><a href="#cb122-3" aria-hidden="true" tabindex="-1"></a>                       <span class="at">crs=</span><span class="dv">4326</span>) <span class="sc">%&gt;%</span></span>
<span id="cb122-4"><a href="#cb122-4" aria-hidden="true" tabindex="-1"></a><span class="fu">st_transform</span>(<span class="at">crs =</span> <span class="dv">3414</span>)</span>
<span id="cb122-5"><a href="#cb122-5" aria-hidden="true" tabindex="-1"></a><span class="fu">glimpse</span>(trip_endings_df)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Rows: 28,000
Columns: 11
Groups: trj_id [28,000]
$ trj_id        &lt;chr&gt; "54687", "81574", "17190", "13793", "39014", "41170", "6…
$ driving_mode  &lt;chr&gt; "car", "car", "car", "car", "car", "car", "car", "car", …
$ osname        &lt;chr&gt; "android", "ios", "android", "android", "ios", "ios", "i…
$ pingtimestamp &lt;dttm&gt; 2019-04-21 23:56:37, 2019-04-21 23:56:33, 2019-04-21 23…
$ speed         &lt;dbl&gt; 1.190000, 17.374184, 9.088703, 5.552219, 14.058416, 12.9…
$ bearing       &lt;int&gt; 299, 117, 201, 180, 179, 73, 210, 53, 163, 347, 22, 193,…
$ accuracy      &lt;dbl&gt; 3.605, 8.000, 4.000, 3.900, 4.000, 5.000, 8.000, 10.000,…
$ weekday       &lt;ord&gt; Sun, Sun, Sun, Sun, Sun, Sun, Sun, Sun, Sun, Sun, Sun, S…
$ end_hr        &lt;fct&gt; 23, 23, 23, 23, 23, 23, 23, 23, 23, 23, 23, 23, 23, 23, …
$ day           &lt;fct&gt; 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, …
$ geometry      &lt;POINT [m]&gt; POINT (22837.7 46850), POINT (43956.34 35640.34), …</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb124"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb124-1"><a href="#cb124-1" aria-hidden="true" tabindex="-1"></a>filtered_road_networks[<span class="dv">1</span><span class="sc">:</span><span class="dv">100</span>,]</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Simple feature collection with 100 features and 11 fields
Geometry type: LINESTRING
Dimension:     XY
Bounding box:  xmin: 6184.054 ymin: 28323.08 xmax: 44422.78 ymax: 47202.77
Projected CRS: SVY21 / Singapore TM
First 10 features:
    osm_id code      fclass              name  ref oneway maxspeed layer bridge
1  4386520 5113     primary      Orchard Road &lt;NA&gt;      F       50     0      F
2  4887867 5122 residential  Hougang Avenue 1 &lt;NA&gt;      B       50     0      F
3  8096835 5113     primary       Scotts Road &lt;NA&gt;      F       60     0      F
4  9584642 5115    tertiary     Keng Lee Road &lt;NA&gt;      F       50     0      F
5  9584847 5153     footway              &lt;NA&gt; &lt;NA&gt;      B        0     0      F
6  9585045 5113     primary       Newton Road &lt;NA&gt;      F       60     0      F
7  9585074 5122 residential      Sarkies Road &lt;NA&gt;      B       50     0      F
8  9585621 5113     primary     Paterson Road &lt;NA&gt;      F       50     0      F
9  9585771 5113     primary Orchard Boulevard &lt;NA&gt;      F       50     0      F
10 9586040 5113     primary     Paterson Road &lt;NA&gt;      F       50     0      F
   tunnel    m                       geometry
1       F TRUE LINESTRING (27637.52 32038....
2       F TRUE LINESTRING (34016.12 36785....
3       F TRUE LINESTRING (28588.71 32765....
4       F TRUE LINESTRING (29165.25 32888....
5       F TRUE LINESTRING (28834.55 32990....
6       F TRUE LINESTRING (28664.35 32858....
7       F TRUE LINESTRING (28433.13 32988....
8       F TRUE LINESTRING (27835.44 31930....
9       F TRUE LINESTRING (28168.89 31418....
10      F TRUE LINESTRING (27685.73 31733....</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb126"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb126-1"><a href="#cb126-1" aria-hidden="true" tabindex="-1"></a>trip_endings_df[<span class="dv">1</span><span class="sc">:</span><span class="dv">100</span>,]</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Simple feature collection with 100 features and 10 fields
Geometry type: POINT
Dimension:     XY
Bounding box:  xmin: 4407.895 ymin: 27568.66 xmax: 45120.65 ymax: 49294.44
Projected CRS: SVY21 / Singapore TM
# A tibble: 100 × 11
# Groups:   trj_id [100]
   trj_id driving_mode osname pingtimestamp       speed bearing accuracy weekday
   &lt;chr&gt;  &lt;chr&gt;        &lt;chr&gt;  &lt;dttm&gt;              &lt;dbl&gt;   &lt;int&gt;    &lt;dbl&gt; &lt;ord&gt;  
 1 54687  car          andro… 2019-04-21 23:56:37  1.19     299     3.60 Sun    
 2 81574  car          ios    2019-04-21 23:56:33 17.4      117     8    Sun    
 3 17190  car          andro… 2019-04-21 23:56:30  9.09     201     4    Sun    
 4 13793  car          andro… 2019-04-21 23:56:25  5.55     180     3.9  Sun    
 5 39014  car          ios    2019-04-21 23:56:11 14.1      179     4    Sun    
 6 41170  car          ios    2019-04-21 23:56:09 13.0       73     5    Sun    
 7 64519  car          ios    2019-04-21 23:55:36 12.6      210     8    Sun    
 8 70461  car          ios    2019-04-21 23:55:29  7.53      53    10    Sun    
 9 41154  car          ios    2019-04-21 23:54:49 14.4      163    32    Sun    
10 5452   car          ios    2019-04-21 23:54:28 12.0      347     8    Sun    
# ℹ 90 more rows
# ℹ 3 more variables: end_hr &lt;fct&gt;, day &lt;fct&gt;, geometry &lt;POINT [m]&gt;</code></pre>
</div>
</div>
</section>
<section id="performing-netkde" class="level3">
<h3 class="anchored" data-anchor-id="performing-netkde"><strong>7.6.3 PERFORMING NETKDE</strong></h3>
<p>We are ready to computer the NetKDE by using the code chunk below.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb128"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb128-1"><a href="#cb128-1" aria-hidden="true" tabindex="-1"></a>densities <span class="ot">&lt;-</span> <span class="fu">nkde</span>(filtered_road_networks[<span class="dv">1</span><span class="sc">:</span><span class="dv">1000</span>,], </span>
<span id="cb128-2"><a href="#cb128-2" aria-hidden="true" tabindex="-1"></a>                  <span class="at">events =</span> trip_endings_df[<span class="dv">1</span><span class="sc">:</span><span class="dv">1000</span>,],</span>
<span id="cb128-3"><a href="#cb128-3" aria-hidden="true" tabindex="-1"></a>                  <span class="at">w =</span> <span class="fu">rep</span>(<span class="dv">1</span>,<span class="fu">nrow</span>(trip_endings_df[<span class="dv">1</span><span class="sc">:</span><span class="dv">1000</span>,])),</span>
<span id="cb128-4"><a href="#cb128-4" aria-hidden="true" tabindex="-1"></a>                  <span class="at">samples =</span> samples,</span>
<span id="cb128-5"><a href="#cb128-5" aria-hidden="true" tabindex="-1"></a>                  <span class="at">kernel_name =</span> <span class="st">"quartic"</span>,</span>
<span id="cb128-6"><a href="#cb128-6" aria-hidden="true" tabindex="-1"></a>                  <span class="at">bw =</span> <span class="dv">300</span>, </span>
<span id="cb128-7"><a href="#cb128-7" aria-hidden="true" tabindex="-1"></a>                  <span class="at">div=</span> <span class="st">"bw"</span>, </span>
<span id="cb128-8"><a href="#cb128-8" aria-hidden="true" tabindex="-1"></a>                  <span class="at">method =</span> <span class="st">"simple"</span>, </span>
<span id="cb128-9"><a href="#cb128-9" aria-hidden="true" tabindex="-1"></a>                  <span class="at">digits =</span> <span class="dv">1</span>, </span>
<span id="cb128-10"><a href="#cb128-10" aria-hidden="true" tabindex="-1"></a>                  <span class="at">tol =</span> <span class="dv">1</span>,</span>
<span id="cb128-11"><a href="#cb128-11" aria-hidden="true" tabindex="-1"></a>                  <span class="at">grid_shape =</span> <span class="fu">c</span>(<span class="dv">1</span>,<span class="dv">1</span>), </span>
<span id="cb128-12"><a href="#cb128-12" aria-hidden="true" tabindex="-1"></a>                  <span class="at">max_depth =</span> <span class="dv">8</span>,</span>
<span id="cb128-13"><a href="#cb128-13" aria-hidden="true" tabindex="-1"></a>                  <span class="at">agg =</span> <span class="dv">5</span>, <span class="co">#we aggregate events within a 5m radius (faster calculation)</span></span>
<span id="cb128-14"><a href="#cb128-14" aria-hidden="true" tabindex="-1"></a>                  <span class="at">sparse =</span> <span class="cn">TRUE</span>,</span>
<span id="cb128-15"><a href="#cb128-15" aria-hidden="true" tabindex="-1"></a>                  <span class="at">verbose =</span> <span class="cn">FALSE</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<section id="visualising-netkde" class="level4">
<h4 class="anchored" data-anchor-id="visualising-netkde"><strong>7.6.3.1 VISUALISING NETKDE</strong></h4>
<p>Before we can visualise the NetKDE values, code chunk below will be used to insert the computed density values (i.e.&nbsp;densities) into <em>samples</em> and <em>lixels</em> objects as <em>density</em> field.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb129"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb129-1"><a href="#cb129-1" aria-hidden="true" tabindex="-1"></a>samples<span class="sc">$</span>density <span class="ot">&lt;-</span> densities</span>
<span id="cb129-2"><a href="#cb129-2" aria-hidden="true" tabindex="-1"></a>lixels<span class="sc">$</span>density <span class="ot">&lt;-</span> densities</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Since svy21 projection system is in meter, the computed density values are very small i.e.&nbsp;0.0000005. The code chunk below is used to resale the density values from number of events per meter to number of events per kilometer.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb130"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb130-1"><a href="#cb130-1" aria-hidden="true" tabindex="-1"></a><span class="co"># rescaling to help the mapping</span></span>
<span id="cb130-2"><a href="#cb130-2" aria-hidden="true" tabindex="-1"></a>samples<span class="sc">$</span>density <span class="ot">&lt;-</span> samples<span class="sc">$</span>density<span class="sc">*</span><span class="dv">1000</span></span>
<span id="cb130-3"><a href="#cb130-3" aria-hidden="true" tabindex="-1"></a>lixels<span class="sc">$</span>density <span class="ot">&lt;-</span> lixels<span class="sc">$</span>density<span class="sc">*</span><span class="dv">1000</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>The code below uses appropriate functions of tmap package to prepare interactive and high cartographic quality map visualisation.</p>
<p>Due to javascript heap memory error when rendering this component it has been comment. Do uncomment it for full results.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb131"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb131-1"><a href="#cb131-1" aria-hidden="true" tabindex="-1"></a><span class="co">#tmap_mode('view')</span></span>
<span id="cb131-2"><a href="#cb131-2" aria-hidden="true" tabindex="-1"></a><span class="co">#tm_shape(lixels)+</span></span>
<span id="cb131-3"><a href="#cb131-3" aria-hidden="true" tabindex="-1"></a>  <span class="co">#tm_lines(col="density")+</span></span>
<span id="cb131-4"><a href="#cb131-4" aria-hidden="true" tabindex="-1"></a><span class="co">#tm_shape(trip_endings_df[1:1000,])+</span></span>
<span id="cb131-5"><a href="#cb131-5" aria-hidden="true" tabindex="-1"></a>  <span class="co">#tm_dots()</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb132"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb132-1"><a href="#cb132-1" aria-hidden="true" tabindex="-1"></a><span class="fu">tmap_mode</span>(<span class="st">'plot'</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
</section>
</section>
</section>
<section id="references" class="level1">
<h1>References</h1>
<ul>
<li><p><a href="https://r4gdsa.netlify.app/chap04.html" class="uri">https://r4gdsa.netlify.app/chap04.html</a></p></li>
<li><p><a href="https://r4gdsa.netlify.app/chap07.html" class="uri">https://r4gdsa.netlify.app/chap07.html</a></p></li>
</ul>


</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      return note.innerHTML;
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->




</body></html>